"""
Risk Analysis — Compliance framework mapping enrichment.

Adds ComplianceMapping and ComplianceDetails fields to each risk finding
by looking up the Subcategory field against 11 compliance frameworks.
"""
from __future__ import annotations

import logging

log = logging.getLogger(__name__)

# ── Maps each risk subcategory → framework control IDs ───────────────────
# 11 frameworks: CIS (Azure Foundations v2.1), NIST-800-53 (Rev 5),
#   NIST-CSF (v2.0), ISO-27001 (2022), PCI-DSS (v4.0), HIPAA,
#   SOC2, GDPR, FedRAMP (Moderate), MCSB (v1.0), CSA-CCM (v4)

_COMPLIANCE_MAP: dict[str, dict[str, list[str]]] = {
    # ── Identity ─────────────────────────────────────────────────────────
    "dormant_accounts": {
        "CIS": ["1.7"],
        "NIST-800-53": ["AC-2(3)", "AC-2(12)"],
        "NIST-CSF": ["PR.AC-1", "DE.CM-3"],
        "ISO-27001": ["A.5.18", "A.8.2"],
        "PCI-DSS": ["8.1.4", "8.2.6"],
        "HIPAA": ["164.312(a)(1)", "164.308(a)(4)(ii)(C)"],
        "SOC2": ["CC6.1", "CC6.2"],
        "GDPR": ["Art.5(1e)", "Art.25(2)"],
        "FedRAMP": ["AC-2(3)", "AC-2"],
        "MCSB": ["PA-4", "IM-1"],
        "CSA-CCM": ["IAM-06", "IAM-12"],
    },
    "overpermissioned_service_principals": {
        "CIS": ["1.22", "1.23"],
        "NIST-800-53": ["AC-6", "AC-6(1)"],
        "NIST-CSF": ["PR.AC-4", "PR.AC-1"],
        "ISO-27001": ["A.5.15", "A.5.18"],
        "PCI-DSS": ["7.1", "7.2.2"],
        "HIPAA": ["164.312(a)(1)", "164.308(a)(3)(i)"],
        "SOC2": ["CC6.1", "CC6.3"],
        "GDPR": ["Art.5(1f)", "Art.25(2)"],
        "FedRAMP": ["AC-6", "AC-6(1)"],
        "MCSB": ["PA-7", "PA-1"],
        "CSA-CCM": ["IAM-05", "IAM-10"],
    },
    "expired_credentials": {
        "CIS": ["1.11", "1.14"],
        "NIST-800-53": ["IA-5(1)", "IA-5"],
        "NIST-CSF": ["PR.AC-1", "PR.AC-7"],
        "ISO-27001": ["A.5.17", "A.8.5"],
        "PCI-DSS": ["8.2.4", "8.3.9"],
        "HIPAA": ["164.312(d)", "164.312(a)(2)(iv)"],
        "SOC2": ["CC6.5", "CC6.1"],
        "GDPR": ["Art.32(1)", "Art.5(1f)"],
        "FedRAMP": ["IA-5(1)", "IA-5"],
        "MCSB": ["IM-3", "IM-1"],
        "CSA-CCM": ["IAM-09", "IAM-02"],
    },
    "expiring_credentials": {
        "CIS": ["1.11", "1.14"],
        "NIST-800-53": ["IA-5(1)", "IA-5"],
        "NIST-CSF": ["PR.AC-1", "PR.AC-7"],
        "ISO-27001": ["A.5.17", "A.8.5"],
        "PCI-DSS": ["8.2.4", "8.3.9"],
        "HIPAA": ["164.312(d)", "164.312(a)(2)(iv)"],
        "SOC2": ["CC6.5", "CC6.1"],
        "GDPR": ["Art.32(1)", "Art.5(1f)"],
        "FedRAMP": ["IA-5(1)", "IA-5"],
        "MCSB": ["IM-3", "IM-1"],
        "CSA-CCM": ["IAM-09", "IAM-02"],
    },
    "mfa_gaps": {
        "CIS": ["1.1.1", "1.2"],
        "NIST-800-53": ["IA-2(1)", "IA-2(2)"],
        "NIST-CSF": ["PR.AC-7", "PR.AC-1"],
        "ISO-27001": ["A.8.5", "A.5.17"],
        "PCI-DSS": ["8.4.2", "8.3.1"],
        "HIPAA": ["164.312(d)", "164.312(a)(2)(i)"],
        "SOC2": ["CC6.1", "CC6.5"],
        "GDPR": ["Art.32(1)", "Art.5(1f)"],
        "FedRAMP": ["IA-2(1)", "IA-2(2)"],
        "MCSB": ["IM-4", "IM-1"],
        "CSA-CCM": ["IAM-02", "IAM-04"],
    },
    "admin_proliferation": {
        "CIS": ["1.3", "1.5"],
        "NIST-800-53": ["AC-6(5)", "AC-2(7)"],
        "NIST-CSF": ["PR.AC-4", "PR.AC-1"],
        "ISO-27001": ["A.5.15", "A.8.2"],
        "PCI-DSS": ["7.1.1", "7.2.2"],
        "HIPAA": ["164.312(a)(1)", "164.308(a)(3)(i)"],
        "SOC2": ["CC6.1", "CC6.3"],
        "GDPR": ["Art.5(1f)", "Art.32(1)"],
        "FedRAMP": ["AC-6(5)", "AC-2(7)"],
        "MCSB": ["PA-1", "PA-7"],
        "CSA-CCM": ["IAM-05", "IAM-10"],
    },
    "guest_user_risk": {
        "CIS": ["1.8", "1.9"],
        "NIST-800-53": ["AC-2(5)", "IA-8"],
        "NIST-CSF": ["PR.AC-1", "PR.AC-4"],
        "ISO-27001": ["A.5.18", "A.5.19"],
        "PCI-DSS": ["7.1", "8.1.5"],
        "HIPAA": ["164.312(a)(1)", "164.308(a)(4)(ii)(B)"],
        "SOC2": ["CC6.1", "CC6.2"],
        "GDPR": ["Art.5(1f)", "Art.28(1)"],
        "FedRAMP": ["AC-2(5)", "IA-8"],
        "MCSB": ["PA-4", "IM-7"],
        "CSA-CCM": ["IAM-06", "IAM-12"],
    },
    "missing_guest_review": {
        "CIS": ["1.8"],
        "NIST-800-53": ["AC-2(3)", "AC-2(12)"],
        "NIST-CSF": ["PR.AC-1", "DE.CM-3"],
        "ISO-27001": ["A.5.18", "A.5.19"],
        "PCI-DSS": ["7.1", "7.1.4"],
        "HIPAA": ["164.312(a)(1)", "164.308(a)(4)(ii)(C)"],
        "SOC2": ["CC6.1", "CC6.2"],
        "GDPR": ["Art.5(1e)", "Art.28(1)"],
        "FedRAMP": ["AC-2(3)", "AC-2(12)"],
        "MCSB": ["PA-4", "GS-6"],
        "CSA-CCM": ["IAM-06", "IAM-12"],
    },
    "high_risk_users": {
        "CIS": ["1.2.1"],
        "NIST-800-53": ["SI-4", "AC-7"],
        "NIST-CSF": ["DE.AE-2", "DE.CM-1"],
        "ISO-27001": ["A.8.16", "A.5.7"],
        "PCI-DSS": ["10.6.1", "11.4"],
        "HIPAA": ["164.308(a)(6)(ii)", "164.312(a)(1)"],
        "SOC2": ["CC6.1", "CC9.1"],
        "GDPR": ["Art.32(1)", "Art.33(1)"],
        "FedRAMP": ["SI-4", "AC-7"],
        "MCSB": ["LT-1", "IM-4"],
        "CSA-CCM": ["TVM-01", "IAM-02"],
    },
    "medium_risk_users": {
        "CIS": ["1.2.1"],
        "NIST-800-53": ["SI-4", "AC-7"],
        "NIST-CSF": ["DE.AE-2", "DE.CM-1"],
        "ISO-27001": ["A.8.16", "A.5.7"],
        "PCI-DSS": ["10.6.1", "11.4"],
        "HIPAA": ["164.308(a)(6)(ii)", "164.312(a)(1)"],
        "SOC2": ["CC6.1", "CC9.1"],
        "GDPR": ["Art.32(1)", "Art.33(1)"],
        "FedRAMP": ["SI-4", "AC-7"],
        "MCSB": ["LT-1", "IM-4"],
        "CSA-CCM": ["TVM-01", "IAM-02"],
    },

    # ── Network ──────────────────────────────────────────────────────────
    "open_management_ports": {
        "CIS": ["6.1", "6.2"],
        "NIST-800-53": ["SC-7", "SC-7(5)"],
        "NIST-CSF": ["PR.AC-5", "PR.PT-4"],
        "ISO-27001": ["A.8.20", "A.8.21"],
        "PCI-DSS": ["1.3.1", "2.2.2"],
        "HIPAA": ["164.312(e)(1)", "164.312(a)(1)"],
        "SOC2": ["CC6.1", "CC6.6"],
        "GDPR": ["Art.32(1)", "Art.25(1)"],
        "FedRAMP": ["SC-7", "SC-7(5)"],
        "MCSB": ["NS-1", "NS-3"],
        "CSA-CCM": ["IVS-03", "IVS-06"],
    },
    "public_storage": {
        "CIS": ["3.7", "3.8"],
        "NIST-800-53": ["AC-3", "SC-7"],
        "NIST-CSF": ["PR.AC-5", "PR.DS-1"],
        "ISO-27001": ["A.8.3", "A.8.20"],
        "PCI-DSS": ["1.3.1", "7.1"],
        "HIPAA": ["164.312(a)(1)", "164.312(e)(1)"],
        "SOC2": ["CC6.1", "CC6.7"],
        "GDPR": ["Art.25(1)", "Art.32(1)"],
        "FedRAMP": ["AC-3", "SC-7"],
        "MCSB": ["DP-9", "NS-1"],
        "CSA-CCM": ["DSP-10", "IVS-03"],
    },
    "webapp_transport_security": {
        "CIS": ["9.2", "9.3"],
        "NIST-800-53": ["SC-8", "SC-8(1)"],
        "NIST-CSF": ["PR.DS-2", "PR.AC-5"],
        "ISO-27001": ["A.8.24", "A.8.20"],
        "PCI-DSS": ["4.1", "4.2.1"],
        "HIPAA": ["164.312(e)(1)", "164.312(e)(2)"],
        "SOC2": ["CC6.7", "CC6.1"],
        "GDPR": ["Art.32(1)", "Art.5(1f)"],
        "FedRAMP": ["SC-8", "SC-8(1)"],
        "MCSB": ["DP-3", "NS-1"],
        "CSA-CCM": ["CEK-03", "DSP-17"],
    },
    "sql_firewall_exposure": {
        "CIS": ["4.1.2", "6.1"],
        "NIST-800-53": ["SC-7", "AC-3"],
        "NIST-CSF": ["PR.AC-5", "PR.PT-4"],
        "ISO-27001": ["A.8.20", "A.8.21"],
        "PCI-DSS": ["1.3.1", "1.2.1"],
        "HIPAA": ["164.312(e)(1)", "164.312(a)(1)"],
        "SOC2": ["CC6.1", "CC6.6"],
        "GDPR": ["Art.32(1)", "Art.25(1)"],
        "FedRAMP": ["SC-7", "SC-7(5)"],
        "MCSB": ["NS-1", "NS-2"],
        "CSA-CCM": ["IVS-03", "IVS-06"],
    },

    # ── Defender ─────────────────────────────────────────────────────────
    "disabled_plans": {
        "CIS": ["2.1.1", "2.1.2"],
        "NIST-800-53": ["SI-4", "RA-5"],
        "NIST-CSF": ["DE.AE-2", "DE.CM-8"],
        "ISO-27001": ["A.8.16", "A.8.8"],
        "PCI-DSS": ["11.4", "6.1"],
        "HIPAA": ["164.308(a)(6)(ii)", "164.308(a)(1)(ii)(D)"],
        "SOC2": ["CC9.1", "CC7.1"],
        "GDPR": ["Art.32(1)", "Art.33(1)"],
        "FedRAMP": ["SI-4", "RA-5"],
        "MCSB": ["LT-1", "PV-5"],
        "CSA-CCM": ["TVM-01", "TVM-02"],
    },
    "security_recommendations": {
        "CIS": ["2.1.1"],
        "NIST-800-53": ["RA-5", "CA-7"],
        "NIST-CSF": ["DE.CM-8", "ID.RA-1"],
        "ISO-27001": ["A.8.8", "A.5.7"],
        "PCI-DSS": ["6.1", "11.4"],
        "HIPAA": ["164.308(a)(1)(ii)(A)", "164.308(a)(8)"],
        "SOC2": ["CC7.1", "CC3.2"],
        "GDPR": ["Art.32(1)", "Art.35(1)"],
        "FedRAMP": ["RA-5", "CA-7"],
        "MCSB": ["PV-5", "GS-3"],
        "CSA-CCM": ["TVM-02", "GRC-01"],
    },
    "low_secure_score": {
        "CIS": ["2.1.1"],
        "NIST-800-53": ["CA-7", "PM-4"],
        "NIST-CSF": ["ID.RA-1", "PR.IP-7"],
        "ISO-27001": ["A.5.7", "A.5.35"],
        "PCI-DSS": ["12.2", "6.1"],
        "HIPAA": ["164.308(a)(8)", "164.308(a)(1)(ii)(A)"],
        "SOC2": ["CC3.2", "CC4.1"],
        "GDPR": ["Art.32(1)", "Art.35(1)"],
        "FedRAMP": ["CA-7", "PM-4"],
        "MCSB": ["GS-3", "PV-5"],
        "CSA-CCM": ["GRC-01", "GRC-02"],
    },

    # ── Config Drift ─────────────────────────────────────────────────────
    "missing_diagnostics": {
        "CIS": ["5.1.2", "5.1.4"],
        "NIST-800-53": ["AU-2", "AU-3"],
        "NIST-CSF": ["DE.AE-1", "DE.AE-3"],
        "ISO-27001": ["A.8.15", "A.8.16"],
        "PCI-DSS": ["10.2", "10.3"],
        "HIPAA": ["164.312(b)", "164.308(a)(1)(ii)(D)"],
        "SOC2": ["CC8.2", "CC7.2"],
        "GDPR": ["Art.30(1)", "Art.5(2)"],
        "FedRAMP": ["AU-2", "AU-3"],
        "MCSB": ["LT-3", "LT-4"],
        "CSA-CCM": ["LOG-01", "LOG-03"],
    },
    "policy_noncompliance": {
        "CIS": ["2.1.1", "5.1"],
        "NIST-800-53": ["CA-7", "CM-6"],
        "NIST-CSF": ["DE.CM-8", "PR.IP-1"],
        "ISO-27001": ["A.5.35", "A.5.36"],
        "PCI-DSS": ["12.1", "12.2"],
        "HIPAA": ["164.308(a)(8)", "164.308(a)(1)(ii)(A)"],
        "SOC2": ["CC3.2", "CC8.1"],
        "GDPR": ["Art.5(2)", "Art.32(1)"],
        "FedRAMP": ["CA-7", "CM-6"],
        "MCSB": ["GS-3", "PV-6"],
        "CSA-CCM": ["GRC-01", "GRC-03"],
    },
    "missing_tags": {
        "CIS": ["1.22"],
        "NIST-800-53": ["CM-8", "PM-5"],
        "NIST-CSF": ["ID.AM-1", "ID.AM-2"],
        "ISO-27001": ["A.5.9", "A.5.10"],
        "PCI-DSS": ["2.4", "12.3.1"],
        "HIPAA": ["164.308(a)(7)(ii)(A)", "164.310(d)(1)"],
        "SOC2": ["CC3.2", "CC6.1"],
        "GDPR": ["Art.30(1)", "Art.5(2)"],
        "FedRAMP": ["CM-8", "PM-5"],
        "MCSB": ["AM-1", "AM-2"],
        "CSA-CCM": ["DSP-01", "GRC-02"],
    },

    # ── Insider Risk ─────────────────────────────────────────────────────
    "irm_not_assessed": {
        "CIS": ["2.1.1"],
        "NIST-800-53": ["PM-12", "IR-4"],
        "NIST-CSF": ["DE.CM-1", "DE.AE-2"],
        "ISO-27001": ["A.6.1", "A.5.7"],
        "PCI-DSS": ["12.10.1", "12.4"],
        "HIPAA": ["164.308(a)(1)(ii)(A)", "164.308(a)(6)(ii)"],
        "SOC2": ["CC9.1", "CC3.2"],
        "GDPR": ["Art.32(1)", "Art.35(1)"],
        "FedRAMP": ["PM-12", "IR-4"],
        "MCSB": ["LT-1", "GS-3"],
        "CSA-CCM": ["TVM-01", "HRS-09"],
    },
    "no_irm_policies": {
        "CIS": ["2.1.1"],
        "NIST-800-53": ["PM-12", "AC-2(12)"],
        "NIST-CSF": ["DE.CM-1", "DE.CM-3"],
        "ISO-27001": ["A.6.1", "A.6.8"],
        "PCI-DSS": ["12.10.1", "12.4"],
        "HIPAA": ["164.308(a)(1)(ii)(A)", "164.308(a)(6)(ii)"],
        "SOC2": ["CC9.1", "CC3.2"],
        "GDPR": ["Art.32(1)", "Art.35(1)"],
        "FedRAMP": ["PM-12", "AC-2(12)"],
        "MCSB": ["LT-1", "GS-3"],
        "CSA-CCM": ["TVM-01", "HRS-09"],
    },
    "active_irm_alerts": {
        "CIS": ["2.1.1"],
        "NIST-800-53": ["IR-4", "IR-5"],
        "NIST-CSF": ["DE.AE-2", "RS.AN-1"],
        "ISO-27001": ["A.5.25", "A.6.8"],
        "PCI-DSS": ["12.10.5", "10.6.1"],
        "HIPAA": ["164.308(a)(6)(ii)", "164.308(a)(6)(i)"],
        "SOC2": ["CC9.1", "CC7.3"],
        "GDPR": ["Art.33(1)", "Art.34(1)"],
        "FedRAMP": ["IR-4", "IR-5"],
        "MCSB": ["LT-1", "IR-1"],
        "CSA-CCM": ["TVM-01", "HRS-09"],
    },
}


# ── Control details for compliance popup ──────────────────────────────────
# Keyed by "FRAMEWORK:control_id" → {title, rationale, recommendation}

_CONTROL_DETAILS: dict[str, dict[str, str]] = {
    # ── CIS Azure Foundations Benchmark v2.1 ──────────────────────────────
    "CIS:1.1.1": {"title": "Ensure MFA is enabled for all privileged users", "rationale": "Privileged accounts without MFA are the primary target for credential-based attacks.", "recommendation": "Create a Conditional Access policy requiring MFA for all admin roles."},
    "CIS:1.2": {"title": "Ensure MFA is enabled for all users", "rationale": "Every user account without MFA is a potential entry point for attackers.", "recommendation": "Enable Security Defaults or create a CA policy requiring MFA for all users."},
    "CIS:1.2.1": {"title": "Ensure risky sign-in policies are configured", "rationale": "Risky sign-in detection identifies compromised accounts in real time.", "recommendation": "Configure Identity Protection sign-in risk policy with MFA remediation."},
    "CIS:1.3": {"title": "Ensure fewer than 5 Global Administrators", "rationale": "Excessive Global Admins expand the blast radius of privilege escalation.", "recommendation": "Limit Global Admins to 2-4 and use PIM for just-in-time access."},
    "CIS:1.5": {"title": "Ensure PIM is used for privileged roles", "rationale": "Permanent privileged assignments violate the principle of just-in-time access.", "recommendation": "Enable PIM and convert permanent assignments to eligible."},
    "CIS:1.7": {"title": "Ensure inactive accounts are disabled", "rationale": "Dormant accounts without recent sign-in activity are attack targets.", "recommendation": "Disable accounts with no sign-in for 90+ days."},
    "CIS:1.8": {"title": "Ensure guest user access is restricted", "rationale": "Guest users may retain access beyond business need without periodic review.", "recommendation": "Configure access reviews for guest users; restrict invitation settings."},
    "CIS:1.9": {"title": "Ensure guest invite restrictions are configured", "rationale": "Unrestricted guest invitations can lead to unmanaged external identities.", "recommendation": "Limit guest invitations to specific admin roles only."},
    "CIS:1.11": {"title": "Ensure app registration secrets have expiry", "rationale": "Non-expiring secrets persist indefinitely if compromised.", "recommendation": "Set credential expiry on all app registrations (max 12 months)."},
    "CIS:1.14": {"title": "Ensure app credentials are rotated regularly", "rationale": "Long-lived credentials increase the window for exploitation.", "recommendation": "Rotate app credentials before expiry and prefer managed identities."},
    "CIS:1.22": {"title": "Ensure least privilege access", "rationale": "Excessive permissions expand the blast radius of compromised accounts.", "recommendation": "Review RBAC assignments and remove Owner/Contributor where not required."},
    "CIS:1.23": {"title": "Ensure custom roles follow least privilege", "rationale": "Overly broad custom roles undermine RBAC effectiveness.", "recommendation": "Audit custom role definitions and restrict actions to those needed."},
    "CIS:2.1.1": {"title": "Ensure Defender for Cloud is enabled", "rationale": "Defender provides threat detection, vulnerability assessment, and security recommendations.", "recommendation": "Enable Microsoft Defender for Cloud Standard tier for all resource types."},
    "CIS:2.1.2": {"title": "Ensure all Defender plans are enabled", "rationale": "Disabled Defender plans leave resource types without threat detection.", "recommendation": "Enable Defender plans for all supported resource types."},
    "CIS:3.7": {"title": "Ensure public blob access is disabled", "rationale": "Public blob access allows anonymous read to data without authentication.", "recommendation": "Disable public blob access on all storage accounts."},
    "CIS:3.8": {"title": "Ensure storage network rules are configured", "rationale": "Default 'Allow' network rules expose storage to any IP address.", "recommendation": "Set default network action to Deny and whitelist trusted networks."},
    "CIS:4.1.2": {"title": "Ensure SQL server firewall rules are restricted", "rationale": "Permissive firewall rules expose SQL servers to the internet.", "recommendation": "Remove 0.0.0.0/0 rules and use private endpoints."},
    "CIS:5.1": {"title": "Ensure Azure Policy is applied consistently", "rationale": "Policy non-compliance indicates configuration drift from organizational standards.", "recommendation": "Review and remediate all non-compliant Azure Policy assignments."},
    "CIS:5.1.2": {"title": "Ensure blob storage logging is enabled", "rationale": "Without logging, unauthorized access to blobs goes undetected.", "recommendation": "Enable diagnostic logging for blob read, write, and delete operations."},
    "CIS:5.1.4": {"title": "Ensure audit log retention is sufficient", "rationale": "Short retention destroys evidence needed for incident investigation.", "recommendation": "Set audit log retention to at least 90 days."},
    "CIS:6.1": {"title": "Ensure NSGs restrict management ports", "rationale": "Open management ports (RDP/SSH) are prime targets for brute-force attacks.", "recommendation": "Restrict NSG rules for ports 22 and 3389 to trusted IPs or use Azure Bastion."},
    "CIS:6.2": {"title": "Ensure NSGs restrict data ports", "rationale": "Open database ports allow direct network attacks on data services.", "recommendation": "Restrict NSG rules for database ports to trusted IPs."},
    "CIS:9.2": {"title": "Ensure web apps enforce HTTPS", "rationale": "HTTP transmits data in plaintext, exposing it to interception.", "recommendation": "Enable HTTPS-only on all App Service web apps."},
    "CIS:9.3": {"title": "Ensure web apps use TLS 1.2+", "rationale": "Older TLS versions have known cryptographic weaknesses.", "recommendation": "Set minimum TLS version to 1.2 on all web apps."},

    # ── NIST 800-53 Rev 5 ────────────────────────────────────────────────
    "NIST-800-53:AC-2": {"title": "Account Management", "rationale": "Proper account management prevents unauthorized access via stale or orphaned accounts.", "recommendation": "Implement automated account lifecycle management with regular reviews."},
    "NIST-800-53:AC-2(3)": {"title": "Disable Accounts", "rationale": "Inactive accounts for 90+ days must be automatically disabled.", "recommendation": "Configure automated workflows to disable inactive accounts."},
    "NIST-800-53:AC-2(5)": {"title": "Inactivity Logout", "rationale": "External accounts must be managed with additional scrutiny.", "recommendation": "Implement guest access reviews and restrict external collaboration."},
    "NIST-800-53:AC-2(7)": {"title": "Privileged User Accounts", "rationale": "Privileged accounts require enhanced monitoring and just-in-time access.", "recommendation": "Enable PIM and limit standing privileged access."},
    "NIST-800-53:AC-2(12)": {"title": "Account Monitoring for Atypical Usage", "rationale": "Atypical account usage may indicate compromise or insider threat.", "recommendation": "Enable Identity Protection and configure risk-based Conditional Access."},
    "NIST-800-53:AC-3": {"title": "Access Enforcement", "rationale": "Access enforcement ensures the principle of least privilege is applied.", "recommendation": "Implement RBAC and Conditional Access to enforce access controls."},
    "NIST-800-53:AC-6": {"title": "Least Privilege", "rationale": "Least privilege limits user access to only what is required.", "recommendation": "Minimize Owner/Contributor assignments and use custom roles."},
    "NIST-800-53:AC-6(1)": {"title": "Authorize Access to Security Functions", "rationale": "Security functions require explicit authorization beyond standard user rights.", "recommendation": "Restrict security admin roles and audit all assignments."},
    "NIST-800-53:AC-6(5)": {"title": "Privileged Accounts", "rationale": "Privileged accounts must be limited to the minimum number necessary.", "recommendation": "Reduce Global Admin count; use role-specific admin roles."},
    "NIST-800-53:AC-7": {"title": "Unsuccessful Logon Attempts", "rationale": "Repeated failed logons may indicate brute-force or credential-stuffing attacks.", "recommendation": "Configure smart lockout and risk-based Conditional Access."},
    "NIST-800-53:AU-2": {"title": "Event Logging", "rationale": "Event logging enables detection and investigation of security events.", "recommendation": "Enable diagnostic settings on all resources that support them."},
    "NIST-800-53:AU-3": {"title": "Content of Audit Records", "rationale": "Audit records must contain sufficient detail for investigation.", "recommendation": "Enable verbose diagnostic logging including identity, timestamp, and outcome."},
    "NIST-800-53:CA-7": {"title": "Continuous Monitoring", "rationale": "Continuous monitoring detects security drift and emerging threats.", "recommendation": "Use Defender for Cloud secure score and policy compliance dashboards."},
    "NIST-800-53:CM-6": {"title": "Configuration Settings", "rationale": "Configuration baselines prevent drift from secure defaults.", "recommendation": "Enforce Azure Policy for required configuration settings."},
    "NIST-800-53:CM-8": {"title": "System Component Inventory", "rationale": "An accurate inventory supports vulnerability management and compliance.", "recommendation": "Tag all resources and maintain a current asset inventory."},
    "NIST-800-53:IA-2(1)": {"title": "Multi-Factor Authentication to Privileged Accounts", "rationale": "MFA prevents credential-only attacks against privileged accounts.", "recommendation": "Enforce MFA via Conditional Access for all admin roles."},
    "NIST-800-53:IA-2(2)": {"title": "Multi-Factor Authentication to Non-Privileged Accounts", "rationale": "All accounts are vulnerable to phishing and credential theft without MFA.", "recommendation": "Enforce MFA for all users via Security Defaults or CA policy."},
    "NIST-800-53:IA-5": {"title": "Authenticator Management", "rationale": "Proper authenticator management prevents credential-based attacks.", "recommendation": "Rotate credentials, set expiry, and use managed identities."},
    "NIST-800-53:IA-5(1)": {"title": "Password-Based Authentication", "rationale": "Password credential lifecycle must be managed to prevent stale credentials.", "recommendation": "Rotate app credentials and set maximum lifetime policies."},
    "NIST-800-53:IA-8": {"title": "Identification and Authentication (Non-Organizational Users)", "rationale": "Guest and external users require validated identities and restricted access.", "recommendation": "Implement guest access reviews and B2B collaboration policies."},
    "NIST-800-53:IR-4": {"title": "Incident Handling", "rationale": "Incident handling capabilities enable timely response to security events.", "recommendation": "Configure alert rules and response playbooks for insider risk alerts."},
    "NIST-800-53:IR-5": {"title": "Incident Monitoring", "rationale": "Ongoing incident monitoring ensures events are tracked to resolution.", "recommendation": "Review and triage insider risk alerts in the compliance portal."},
    "NIST-800-53:PM-4": {"title": "Plan of Action and Milestones", "rationale": "Tracking remediation progress ensures security gaps are addressed.", "recommendation": "Address Defender recommendations systematically to improve secure score."},
    "NIST-800-53:PM-5": {"title": "Information System Inventory", "rationale": "Maintaining an accurate inventory supports vulnerability assessment.", "recommendation": "Tag all resources for ownership and classification."},
    "NIST-800-53:PM-12": {"title": "Insider Threat Program", "rationale": "An insider threat program detects and responds to malicious insiders.", "recommendation": "Deploy Insider Risk Management in Microsoft Purview."},
    "NIST-800-53:RA-5": {"title": "Vulnerability Monitoring and Scanning", "rationale": "Vulnerability scanning identifies exploitable weaknesses.", "recommendation": "Enable Defender for Cloud and address high-severity recommendations."},
    "NIST-800-53:SC-7": {"title": "Boundary Protection", "rationale": "Network boundaries prevent unauthorized external access and lateral movement.", "recommendation": "Implement NSGs, Azure Firewall, and private endpoints."},
    "NIST-800-53:SC-7(5)": {"title": "Deny by Default / Allow by Exception", "rationale": "Default deny policies prevent unauthorized network access.", "recommendation": "Set default NSG and firewall rules to deny, allow only by exception."},
    "NIST-800-53:SC-8": {"title": "Transmission Confidentiality and Integrity", "rationale": "Data in transit must be protected from interception and tampering.", "recommendation": "Enforce HTTPS/TLS 1.2+ for all communications."},
    "NIST-800-53:SC-8(1)": {"title": "Cryptographic Protection", "rationale": "Cryptographic protection of transmitted data prevents eavesdropping.", "recommendation": "Enforce TLS 1.2+ and disable legacy protocols."},
    "NIST-800-53:SI-4": {"title": "System Monitoring", "rationale": "System monitoring detects attacks, anomalies, and policy violations.", "recommendation": "Enable Defender for Cloud and configure threat detection alerts."},

    # ── NIST CSF 2.0 ─────────────────────────────────────────────────────
    "NIST-CSF:PR.AC-1": {"title": "Access Control Policy", "rationale": "Access control policies define how identities and credentials are managed.", "recommendation": "Implement centralized IAM with MFA and credential management."},
    "NIST-CSF:PR.AC-4": {"title": "Access Permissions and Authorizations", "rationale": "Access permissions must reflect the principle of least privilege.", "recommendation": "Review RBAC assignments and remove excessive permissions."},
    "NIST-CSF:PR.AC-5": {"title": "Network Integrity Protection", "rationale": "Network integrity requires segmentation and access restrictions.", "recommendation": "Implement network segmentation with private endpoints and firewall rules."},
    "NIST-CSF:PR.AC-7": {"title": "Authentication", "rationale": "Users and devices are authenticated before access is granted.", "recommendation": "Enforce MFA and certificate-based authentication."},
    "NIST-CSF:PR.DS-1": {"title": "Data-at-Rest Protection", "rationale": "Data-at-rest must be encrypted and access-controlled.", "recommendation": "Enable encryption at rest and implement data classification."},
    "NIST-CSF:PR.DS-2": {"title": "Data-in-Transit Protection", "rationale": "Data-in-transit must be protected through strong encryption.", "recommendation": "Enforce TLS 1.2+ on all endpoints and disable plaintext protocols."},
    "NIST-CSF:PR.IP-1": {"title": "Baseline Configuration", "rationale": "Baseline configurations prevent drift from secure defaults.", "recommendation": "Enforce Azure Policy for configuration compliance."},
    "NIST-CSF:PR.IP-7": {"title": "Protection Processes Improvement", "rationale": "Continuous improvement of protection processes addresses emerging threats.", "recommendation": "Regularly review and improve secure score and policy compliance."},
    "NIST-CSF:PR.PT-4": {"title": "Communications and Control Networks", "rationale": "Network communications must be protected and monitored.", "recommendation": "Use NSGs and Azure Firewall to control network traffic."},
    "NIST-CSF:DE.AE-1": {"title": "Audit Logging Baseline", "rationale": "A baseline of operations is maintained for anomaly detection.", "recommendation": "Enable diagnostic logging on all resources."},
    "NIST-CSF:DE.AE-2": {"title": "Analyzed Events", "rationale": "Detected events are analyzed to understand attack methods.", "recommendation": "Enable Defender for Cloud and Identity Protection."},
    "NIST-CSF:DE.AE-3": {"title": "Event Data Aggregation", "rationale": "Event data from multiple sources is aggregated for correlation.", "recommendation": "Send all logs to a centralized Log Analytics workspace."},
    "NIST-CSF:DE.CM-1": {"title": "Network Monitoring", "rationale": "The network is monitored to detect potential security events.", "recommendation": "Enable NSG flow logs and Defender for Cloud network monitoring."},
    "NIST-CSF:DE.CM-3": {"title": "Personnel Activity Monitoring", "rationale": "Personnel activity is monitored to detect insider threats.", "recommendation": "Deploy Insider Risk Management and enable user activity monitoring."},
    "NIST-CSF:DE.CM-8": {"title": "Vulnerability Scans", "rationale": "Vulnerability scans identify weaknesses in resources.", "recommendation": "Enable Defender vulnerability assessments on all supported resources."},
    "NIST-CSF:ID.AM-1": {"title": "Asset Inventory", "rationale": "Physical and virtual assets must be inventoried.", "recommendation": "Tag all Azure resources for ownership and classification."},
    "NIST-CSF:ID.AM-2": {"title": "Software Platform Inventory", "rationale": "Software platforms and applications must be inventoried.", "recommendation": "Use Azure Resource Graph to maintain a current asset inventory."},
    "NIST-CSF:ID.RA-1": {"title": "Asset Vulnerabilities Identified", "rationale": "Vulnerabilities in assets are identified and documented.", "recommendation": "Address all Defender for Cloud security recommendations."},
    "NIST-CSF:RS.AN-1": {"title": "Notifications from Detection Systems", "rationale": "Notifications from detection systems are investigated.", "recommendation": "Triage and investigate all insider risk and security alerts."},

    # ── ISO 27001:2022 ───────────────────────────────────────────────────
    "ISO-27001:A.5.7": {"title": "Threat intelligence", "rationale": "Threat intelligence informs risk assessment and security controls.", "recommendation": "Enable Defender for Cloud and Threat Intelligence feeds."},
    "ISO-27001:A.5.9": {"title": "Inventory of information assets", "rationale": "An accurate asset inventory supports governance and risk management.", "recommendation": "Tag all resources and maintain a configuration management database."},
    "ISO-27001:A.5.10": {"title": "Acceptable use of information assets", "rationale": "Acceptable use policies ensure resources are used appropriately.", "recommendation": "Define and enforce tag policies for resource classification."},
    "ISO-27001:A.5.15": {"title": "Access control", "rationale": "Access control ensures only authorized individuals access information assets.", "recommendation": "Implement RBAC and Conditional Access policies."},
    "ISO-27001:A.5.17": {"title": "Authentication information", "rationale": "Strong authentication prevents unauthorized access to systems and data.", "recommendation": "Enforce MFA and implement strong credential policies."},
    "ISO-27001:A.5.18": {"title": "Access rights", "rationale": "Access rights must follow the principle of least privilege.", "recommendation": "Review role assignments regularly and minimize privileged access."},
    "ISO-27001:A.5.19": {"title": "Information security in supplier relationships", "rationale": "External identities require controlled access and periodic review.", "recommendation": "Implement access reviews for guest and external users."},
    "ISO-27001:A.5.25": {"title": "Assessment and decision on information security events", "rationale": "Security events must be assessed and triaged appropriately.", "recommendation": "Investigate all insider risk and security alerts within SLA."},
    "ISO-27001:A.5.35": {"title": "Independent review of information security", "rationale": "Independent reviews validate the effectiveness of security controls.", "recommendation": "Use Defender secure score as input for independent security reviews."},
    "ISO-27001:A.5.36": {"title": "Compliance with policies and standards", "rationale": "Compliance monitoring ensures adherence to organizational policies.", "recommendation": "Monitor Azure Policy compliance and remediate violations."},
    "ISO-27001:A.6.1": {"title": "Screening", "rationale": "Personnel screening and insider risk monitoring protect against insider threats.", "recommendation": "Deploy Insider Risk Management for user activity monitoring."},
    "ISO-27001:A.6.8": {"title": "Information security event reporting", "rationale": "Security events must be reported and escalated appropriately.", "recommendation": "Configure alert notifications for insider risk events."},
    "ISO-27001:A.8.2": {"title": "Privileged access rights", "rationale": "Privileged access must be restricted and monitored.", "recommendation": "Use PIM and limit standing admin assignments."},
    "ISO-27001:A.8.5": {"title": "Secure authentication", "rationale": "Secure authentication mechanisms prevent unauthorized access.", "recommendation": "Enforce MFA for all users and phishing-resistant MFA for admins."},
    "ISO-27001:A.8.8": {"title": "Management of technical vulnerabilities", "rationale": "Technical vulnerabilities must be identified and addressed.", "recommendation": "Address all Defender high-severity security recommendations."},
    "ISO-27001:A.8.15": {"title": "Logging", "rationale": "Logging provides audit trails for security monitoring and incident investigation.", "recommendation": "Enable diagnostic settings on all resources."},
    "ISO-27001:A.8.16": {"title": "Monitoring activities", "rationale": "Monitoring enables detection of anomalous behavior and security incidents.", "recommendation": "Configure Azure Monitor alerts and threat detection."},
    "ISO-27001:A.8.20": {"title": "Networks security", "rationale": "Network security controls protect information in transit and at rest.", "recommendation": "Implement network segmentation, NSGs, and firewall rules."},
    "ISO-27001:A.8.21": {"title": "Security of network services", "rationale": "Network services must enforce confidentiality and integrity.", "recommendation": "Use Azure Bastion, private endpoints, and network encryption."},
    "ISO-27001:A.8.24": {"title": "Use of cryptography", "rationale": "Cryptography protects the confidentiality and integrity of information.", "recommendation": "Enable encryption for data at rest and in transit with TLS 1.2+."},
    "ISO-27001:A.8.3": {"title": "Information access restriction", "rationale": "Storage containers must not allow anonymous public access.", "recommendation": "Set container access to Private and enforce authentication."},

    # ── PCI-DSS v4.0 ─────────────────────────────────────────────────────
    "PCI-DSS:1.2.1": {"title": "Restrict inbound/outbound traffic", "rationale": "Unrestricted traffic enables data exfiltration.", "recommendation": "Configure firewall and NSG rules to restrict traffic."},
    "PCI-DSS:1.3.1": {"title": "Restrict inbound access to CDE", "rationale": "Direct inbound access to the cardholder data environment increases breach risk.", "recommendation": "Restrict inbound CDE access to authorized connections only."},
    "PCI-DSS:2.2.2": {"title": "Manage default accounts", "rationale": "Default management ports enable unauthorized access.", "recommendation": "Disable default management port access and use secure alternatives."},
    "PCI-DSS:2.4": {"title": "Inventory of system components", "rationale": "A complete inventory is needed for vulnerability management.", "recommendation": "Tag all resources to maintain an up-to-date inventory."},
    "PCI-DSS:4.1": {"title": "Use strong cryptography for transmission", "rationale": "Weak encryption exposes data in transit.", "recommendation": "Enforce TLS 1.2+ for all endpoints."},
    "PCI-DSS:4.2.1": {"title": "Strong cryptography for all transmissions", "rationale": "All public-facing endpoints must use strong encryption.", "recommendation": "Enforce HTTPS-only and TLS 1.2+ on all web apps."},
    "PCI-DSS:6.1": {"title": "Identify and rate vulnerabilities", "rationale": "Known vulnerabilities must be identified and prioritized.", "recommendation": "Address all Defender for Cloud recommendations by severity."},
    "PCI-DSS:7.1": {"title": "Limit access to system components", "rationale": "Access must be limited to those with business need.", "recommendation": "Implement least-privilege RBAC and access reviews."},
    "PCI-DSS:7.1.1": {"title": "Define access needs by role", "rationale": "Access needs must be defined for each role.", "recommendation": "Document required access for each admin role and enforce with RBAC."},
    "PCI-DSS:7.1.4": {"title": "Must be properly authorized and privileged", "rationale": "Periodic access reviews validate continued access need.", "recommendation": "Configure recurring access reviews for privileged and guest accounts."},
    "PCI-DSS:7.2.2": {"title": "Assign access based on job classification", "rationale": "Access assignments must align with job responsibilities.", "recommendation": "Use role-based access control aligned to job functions."},
    "PCI-DSS:8.1.4": {"title": "Remove/disable inactive accounts in 90 days", "rationale": "Inactive accounts are attack vectors if not removed.", "recommendation": "Disable or remove accounts inactive for 90+ days."},
    "PCI-DSS:8.1.5": {"title": "Manage third-party remote access", "rationale": "Third-party accounts must be monitored and disabled when not in use.", "recommendation": "Implement guest access reviews and expiration policies."},
    "PCI-DSS:8.2.4": {"title": "Strong authentication for identity verification", "rationale": "Credential lifecycle must be managed to prevent stale credentials.", "recommendation": "Set credential expiry and rotate regularly."},
    "PCI-DSS:8.2.6": {"title": "Inactive accounts are managed", "rationale": "Dormant accounts exceeding 90 days must be deactivated.", "recommendation": "Automate deactivation of accounts inactive for 90+ days."},
    "PCI-DSS:8.3.1": {"title": "MFA for all access to CDE", "rationale": "MFA prevents credential-only attacks on cardholder data environment.", "recommendation": "Enforce MFA for all users via Conditional Access."},
    "PCI-DSS:8.3.9": {"title": "MFA for all remote access", "rationale": "Remote access without MFA is vulnerable to credential theft.", "recommendation": "Require MFA for all remote and VPN access."},
    "PCI-DSS:8.4.2": {"title": "MFA for all remote network access", "rationale": "Remote access to the CDE must use multi-factor authentication.", "recommendation": "Configure Conditional Access policies requiring MFA."},
    "PCI-DSS:10.2": {"title": "Implement automated audit trails", "rationale": "Without audit trails, security events go undetected.", "recommendation": "Enable diagnostic logging on all resources."},
    "PCI-DSS:10.3": {"title": "Protect audit trail from modification", "rationale": "Modifiable logs can be altered to conceal attacker activity.", "recommendation": "Enable immutability on audit log storage."},
    "PCI-DSS:10.6.1": {"title": "Review logs for anomalies", "rationale": "Log review detects potential security incidents.", "recommendation": "Configure alerts for anomalous activity in Identity Protection."},
    "PCI-DSS:11.4": {"title": "Intrusion detection and prevention", "rationale": "Without IDS/IPS, network attacks go undetected.", "recommendation": "Enable Defender for Cloud and configure alert notifications."},
    "PCI-DSS:12.1": {"title": "Information security policy", "rationale": "A security policy establishes the organization's security program.", "recommendation": "Enforce Azure Policy assignments aligned to security standards."},
    "PCI-DSS:12.2": {"title": "Risk assessment process", "rationale": "Annual risk assessments identify new threats and vulnerabilities.", "recommendation": "Use Defender secure score to identify and remediate risks."},
    "PCI-DSS:12.3.1": {"title": "Targeted risk analysis", "rationale": "Targeted analysis validates the effectiveness of specific controls.", "recommendation": "Review specific control effectiveness through compliance dashboards."},
    "PCI-DSS:12.4": {"title": "Service provider responsibility", "rationale": "Service providers must protect customer data.", "recommendation": "Monitor insider risk indicators for privileged personnel."},
    "PCI-DSS:12.10.1": {"title": "Incident response plan exists", "rationale": "An incident response plan enables timely response to security events.", "recommendation": "Ensure Insider Risk Management is deployed as part of the IR plan."},
    "PCI-DSS:12.10.5": {"title": "Alerts from security monitoring", "rationale": "Security alerts must be triaged and investigated.", "recommendation": "Monitor and triage all Defender and insider risk alerts."},

    # ── HIPAA Security Rule ───────────────────────────────────────────────
    "HIPAA:164.308(a)(1)(ii)(A)": {"title": "Risk Analysis", "rationale": "HIPAA requires an accurate risk analysis of ePHI.", "recommendation": "Use Defender for Cloud and policy compliance to assess risk."},
    "HIPAA:164.308(a)(1)(ii)(D)": {"title": "Information System Activity Review", "rationale": "HIPAA requires regular review of system activity records.", "recommendation": "Enable and review diagnostic logs and audit trails."},
    "HIPAA:164.308(a)(3)(i)": {"title": "Workforce Security", "rationale": "Access to ePHI must be limited to authorized workforce members.", "recommendation": "Implement RBAC with least privilege."},
    "HIPAA:164.308(a)(4)(ii)(B)": {"title": "Access Authorization", "rationale": "Policies must grant access based on job function.", "recommendation": "Restrict guest and external access to necessary resources."},
    "HIPAA:164.308(a)(4)(ii)(C)": {"title": "Access Establishment and Modification", "rationale": "Access rights must be reviewed and modified as needed.", "recommendation": "Conduct regular access reviews for all user types."},
    "HIPAA:164.308(a)(6)(i)": {"title": "Security Incident Procedures", "rationale": "HIPAA requires procedures for reporting and responding to security incidents.", "recommendation": "Establish incident response procedures for insider risk alerts."},
    "HIPAA:164.308(a)(6)(ii)": {"title": "Response and Reporting", "rationale": "Security incidents must be identified, reported, and responded to.", "recommendation": "Enable Defender alerts and investigate all security events."},
    "HIPAA:164.308(a)(7)(ii)(A)": {"title": "Data Backup Plan", "rationale": "HIPAA requires exact copies of ePHI to be retrievable.", "recommendation": "Tag resources to identify ePHI systems requiring backup compliance."},
    "HIPAA:164.308(a)(8)": {"title": "Evaluation", "rationale": "HIPAA requires periodic evaluation of security controls.", "recommendation": "Review Defender secure score and policy compliance regularly."},
    "HIPAA:164.310(d)(1)": {"title": "Device and Media Controls", "rationale": "Movement of ePHI-containing hardware and media must be tracked.", "recommendation": "Maintain an accurate inventory of all ePHI-processing resources."},
    "HIPAA:164.312(a)(1)": {"title": "Access Control", "rationale": "Technical policies must allow only authorized access to ePHI.", "recommendation": "Implement RBAC with least-privilege and Conditional Access."},
    "HIPAA:164.312(a)(2)(i)": {"title": "Unique User Identification", "rationale": "Each user must be uniquely identified.", "recommendation": "Use Entra ID for centralized identity management."},
    "HIPAA:164.312(a)(2)(iv)": {"title": "Encryption and Decryption", "rationale": "HIPAA requires encryption for ePHI.", "recommendation": "Encrypt all ePHI at rest using AES-256 or equivalent."},
    "HIPAA:164.312(b)": {"title": "Audit Controls", "rationale": "HIPAA requires audit trails for ePHI access.", "recommendation": "Enable logging and audit trails on all systems containing ePHI."},
    "HIPAA:164.312(d)": {"title": "Person or Entity Authentication", "rationale": "Persons accessing ePHI must be verified.", "recommendation": "Use Azure AD authentication with MFA."},
    "HIPAA:164.312(e)(1)": {"title": "Transmission Security", "rationale": "ePHI in transit must be protected.", "recommendation": "Enforce TLS 1.2+ and network segmentation."},
    "HIPAA:164.312(e)(2)": {"title": "Encryption of ePHI in Transit", "rationale": "All ePHI transmissions must use encryption.", "recommendation": "Enforce HTTPS-only on all web applications."},

    # ── SOC 2 Type II ────────────────────────────────────────────────────
    "SOC2:CC3.2": {"title": "Risk Identification and Assessment", "rationale": "Risks must be identified and assessed to achieve service commitments.", "recommendation": "Use Defender secure score and compliance dashboards."},
    "SOC2:CC4.1": {"title": "Monitoring Activities", "rationale": "Controls must be monitored for effective operation.", "recommendation": "Review Defender secure score trends and compliance state."},
    "SOC2:CC6.1": {"title": "Logical Access Controls", "rationale": "Logical access controls restrict system access to authorized users.", "recommendation": "Implement RBAC, Conditional Access, and network rules."},
    "SOC2:CC6.2": {"title": "Access Provisioning and De-provisioning", "rationale": "Access must be provisioned based on authorization and revoked when no longer needed.", "recommendation": "Implement access reviews and automated de-provisioning."},
    "SOC2:CC6.3": {"title": "Removal or Modification of Access", "rationale": "Access must be reviewed and revoked when no longer needed.", "recommendation": "Conduct regular access reviews and remove excessive permissions."},
    "SOC2:CC6.5": {"title": "Access Credentials", "rationale": "Credentials must be managed securely through their lifecycle.", "recommendation": "Use managed identities, set key expiry, and rotate credentials."},
    "SOC2:CC6.6": {"title": "System Boundary Protection", "rationale": "System components are protected from external threats.", "recommendation": "Use NSGs, firewalls, and network segmentation."},
    "SOC2:CC6.7": {"title": "Transmission Security", "rationale": "Data in transit must use encrypted communication.", "recommendation": "Enforce HTTPS/TLS 1.2+ on all endpoints."},
    "SOC2:CC7.1": {"title": "Detection of Anomalies", "rationale": "Anomalous activities must be detected and reported.", "recommendation": "Enable Defender for Cloud and vulnerability assessments."},
    "SOC2:CC7.2": {"title": "Monitoring for Anomalies", "rationale": "System activity must be monitored for anomalous events.", "recommendation": "Enable diagnostic logging and configure monitoring alerts."},
    "SOC2:CC7.3": {"title": "Evaluation of Detected Anomalies", "rationale": "Detected anomalies must be evaluated and responded to.", "recommendation": "Investigate all insider risk and security alerts."},
    "SOC2:CC8.1": {"title": "Change Management", "rationale": "Changes must be controlled and auditable.", "recommendation": "Enforce Azure Policy and monitor compliance state."},
    "SOC2:CC8.2": {"title": "Sensitive Access Logging", "rationale": "Access to sensitive data must be logged for accountability.", "recommendation": "Enable diagnostic logging and audit trails."},
    "SOC2:CC9.1": {"title": "Incident Detection", "rationale": "Security incidents must be detected and escalated.", "recommendation": "Enable Defender for Cloud, Identity Protection, and IRM."},

    # ── GDPR ─────────────────────────────────────────────────────────────
    "GDPR:Art.5(1e)": {"title": "Storage Limitation", "rationale": "Personal data must not be kept longer than necessary.", "recommendation": "Disable or remove dormant accounts to comply with storage limitation."},
    "GDPR:Art.5(1f)": {"title": "Integrity and Confidentiality", "rationale": "Personal data must be processed with appropriate security.", "recommendation": "Implement encryption, MFA, and access controls."},
    "GDPR:Art.5(2)": {"title": "Accountability", "rationale": "The controller must be able to demonstrate compliance.", "recommendation": "Enable logging, tagging, and policy compliance monitoring."},
    "GDPR:Art.25(1)": {"title": "Data Protection by Design", "rationale": "Appropriate technical measures must be implemented from the design phase.", "recommendation": "Implement private endpoints, encryption, and access controls."},
    "GDPR:Art.25(2)": {"title": "Data Protection by Default", "rationale": "Only necessary personal data must be processed.", "recommendation": "Implement least-privilege access and data minimization."},
    "GDPR:Art.28(1)": {"title": "Processor Requirements", "rationale": "External processors must provide sufficient guarantees.", "recommendation": "Review and restrict guest/external access to personal data."},
    "GDPR:Art.30(1)": {"title": "Records of Processing Activities", "rationale": "Processing activities must be documented.", "recommendation": "Enable diagnostic logging and maintain audit trails."},
    "GDPR:Art.32(1)": {"title": "Security of Processing", "rationale": "Appropriate technical and organizational measures must ensure security.", "recommendation": "Enable Defender, MFA, encryption, and access controls."},
    "GDPR:Art.33(1)": {"title": "Notification of Personal Data Breach", "rationale": "Breaches must be reported to supervisory authorities within 72 hours.", "recommendation": "Configure alert notifications and incident response procedures."},
    "GDPR:Art.34(1)": {"title": "Communication of Breach to Data Subject", "rationale": "High-risk breaches must be communicated to affected individuals.", "recommendation": "Investigate insider risk alerts promptly and assess breach impact."},
    "GDPR:Art.35(1)": {"title": "Data Protection Impact Assessment", "rationale": "A DPIA is required for high-risk processing activities.", "recommendation": "Use Defender secure score and compliance assessments."},

    # ── FedRAMP Moderate ──────────────────────────────────────────────────
    "FedRAMP:AC-2": {"title": "Account Management", "rationale": "FedRAMP requires automated account lifecycle management.", "recommendation": "Implement automated workflows to manage account provisioning and termination."},
    "FedRAMP:AC-2(3)": {"title": "Disable Accounts", "rationale": "Inactive accounts must be disabled within 90 days.", "recommendation": "Automate disabling of inactive accounts."},
    "FedRAMP:AC-2(5)": {"title": "Inactivity Logout", "rationale": "External accounts must be reviewed and restricted.", "recommendation": "Implement guest access reviews and session policies."},
    "FedRAMP:AC-2(7)": {"title": "Privileged User Accounts", "rationale": "Privileged accounts require enhanced controls.", "recommendation": "Use PIM for just-in-time privileged access."},
    "FedRAMP:AC-2(12)": {"title": "Account Monitoring", "rationale": "Account usage must be monitored for atypical activity.", "recommendation": "Enable Identity Protection and risk-based policies."},
    "FedRAMP:AC-3": {"title": "Access Enforcement", "rationale": "Access to information must be enforced through technical controls.", "recommendation": "Use RBAC, network rules, and Conditional Access."},
    "FedRAMP:AC-6": {"title": "Least Privilege", "rationale": "Least privilege limits authorized access to needed resources.", "recommendation": "Review and minimize RBAC assignments."},
    "FedRAMP:AC-6(1)": {"title": "Authorize Access to Security Functions", "rationale": "Security functions require explicit authorization.", "recommendation": "Restrict admin role assignments to minimum necessary."},
    "FedRAMP:AC-6(5)": {"title": "Privileged Accounts", "rationale": "Privileged accounts must be limited.", "recommendation": "Limit Global Admins and use PIM."},
    "FedRAMP:AC-7": {"title": "Unsuccessful Logon Attempts", "rationale": "Failed logon patterns indicate brute-force attacks.", "recommendation": "Configure smart lockout and risk-based policies."},
    "FedRAMP:AU-2": {"title": "Event Logging", "rationale": "Auditable events must be logged.", "recommendation": "Enable diagnostic settings on all resources."},
    "FedRAMP:AU-3": {"title": "Content of Audit Records", "rationale": "Audit records must contain sufficient detail.", "recommendation": "Enable verbose diagnostic logging."},
    "FedRAMP:CA-7": {"title": "Continuous Monitoring", "rationale": "Continuous monitoring detects security drift.", "recommendation": "Use Defender secure score and policy compliance."},
    "FedRAMP:CM-6": {"title": "Configuration Settings", "rationale": "Configuration baselines prevent security drift.", "recommendation": "Enforce Azure Policy for required settings."},
    "FedRAMP:CM-8": {"title": "System Component Inventory", "rationale": "An accurate inventory is required.", "recommendation": "Tag all resources and maintain inventory."},
    "FedRAMP:IA-2(1)": {"title": "MFA for Privileged Accounts", "rationale": "MFA is required for all privileged access.", "recommendation": "Enforce MFA via Conditional Access for admin roles."},
    "FedRAMP:IA-2(2)": {"title": "MFA for Non-Privileged Accounts", "rationale": "MFA is required for non-privileged access.", "recommendation": "Enforce MFA for all users."},
    "FedRAMP:IA-5": {"title": "Authenticator Management", "rationale": "Credentials must be managed through their lifecycle.", "recommendation": "Rotate credentials and use managed identities."},
    "FedRAMP:IA-5(1)": {"title": "Password-Based Authentication", "rationale": "Password credentials must have limited lifetime.", "recommendation": "Set credential expiry on all app registrations."},
    "FedRAMP:IA-8": {"title": "Non-Organizational Users Authentication", "rationale": "External users must be authenticated and authorized.", "recommendation": "Implement B2B collaboration policies and access reviews."},
    "FedRAMP:IR-4": {"title": "Incident Handling", "rationale": "Incident handling enables response to security events.", "recommendation": "Configure playbooks for insider risk and security alerts."},
    "FedRAMP:IR-5": {"title": "Incident Monitoring", "rationale": "Incidents must be tracked to resolution.", "recommendation": "Monitor and triage all alerts in compliance portal."},
    "FedRAMP:PM-4": {"title": "Plan of Action and Milestones", "rationale": "Remediation tracking ensures gaps are addressed.", "recommendation": "Track Defender recommendations as POA&M items."},
    "FedRAMP:PM-5": {"title": "System Inventory", "rationale": "Complete system inventory is required.", "recommendation": "Tag all resources and maintain accurate inventory."},
    "FedRAMP:PM-12": {"title": "Insider Threat Program", "rationale": "An insider threat program is required.", "recommendation": "Deploy Insider Risk Management in Purview."},
    "FedRAMP:RA-5": {"title": "Vulnerability Monitoring and Scanning", "rationale": "Systems must be scanned for vulnerabilities.", "recommendation": "Enable Defender for Cloud vulnerability assessments."},
    "FedRAMP:SC-7": {"title": "Boundary Protection", "rationale": "Network boundaries restrict unauthorized access.", "recommendation": "Use NSGs, Azure Firewall, and private endpoints."},
    "FedRAMP:SC-7(5)": {"title": "Deny by Default", "rationale": "Default deny policies prevent unauthorized network access.", "recommendation": "Set default firewall rules to deny."},
    "FedRAMP:SC-8": {"title": "Transmission Confidentiality", "rationale": "Data in transit must be encrypted.", "recommendation": "Enforce TLS 1.2+ on all endpoints."},
    "FedRAMP:SC-8(1)": {"title": "Cryptographic Protection", "rationale": "Cryptographic mechanisms protect transmitted data.", "recommendation": "Enforce TLS 1.2+ and disable legacy protocols."},
    "FedRAMP:SI-4": {"title": "System Monitoring", "rationale": "System monitoring detects attacks and policy violations.", "recommendation": "Enable Defender for Cloud and Identity Protection."},

    # ── MCSB (Microsoft Cloud Security Benchmark) ────────────────────────
    "MCSB:AM-1": {"title": "Track asset inventory", "rationale": "Asset tracking supports governance and vulnerability management.", "recommendation": "Tag all Azure resources with required metadata."},
    "MCSB:AM-2": {"title": "Use only approved services", "rationale": "Unapproved services may lack security controls.", "recommendation": "Enforce allowed resource types through Azure Policy."},
    "MCSB:DP-3": {"title": "Encrypt sensitive data in transit", "rationale": "Data in transit must be encrypted.", "recommendation": "Enforce TLS 1.2+ and HTTPS-only."},
    "MCSB:DP-9": {"title": "Storage public access control", "rationale": "Public access to storage exposes data.", "recommendation": "Disable public blob access on all storage accounts."},
    "MCSB:GS-3": {"title": "Align roles, responsibilities to framework", "rationale": "Security responsibilities must be clearly defined.", "recommendation": "Review and remediate policy compliance and secure score."},
    "MCSB:GS-6": {"title": "Define and implement identity strategy", "rationale": "A clear identity strategy enables consistent access control.", "recommendation": "Implement access reviews and guest user policies."},
    "MCSB:IM-1": {"title": "Use centralized identity and authentication", "rationale": "Centralized identity provides consistent access control and audit.", "recommendation": "Use Entra ID authentication and disable local accounts."},
    "MCSB:IM-3": {"title": "Manage application identities securely", "rationale": "Application identities must use managed identities or certificates.", "recommendation": "Use managed identities and set credential expiry."},
    "MCSB:IM-4": {"title": "Authenticate server and services", "rationale": "MFA must be enforced for all authentication scenarios.", "recommendation": "Enforce MFA via Conditional Access for all users."},
    "MCSB:IM-7": {"title": "Restrict resource access based on conditions", "rationale": "Conditional Access enforces context-based access decisions.", "recommendation": "Configure risk-based Conditional Access policies."},
    "MCSB:IR-1": {"title": "Preparation – update incident response plan", "rationale": "Incident response plans must be current.", "recommendation": "Include insider risk scenarios in the incident response plan."},
    "MCSB:LT-1": {"title": "Enable threat detection capabilities", "rationale": "Threat detection surfaces attacks and anomalous behavior.", "recommendation": "Enable Defender for Cloud and IRM."},
    "MCSB:LT-3": {"title": "Enable logging for security investigation", "rationale": "Security logs provide evidence for investigation.", "recommendation": "Enable diagnostic settings and audit logging."},
    "MCSB:LT-4": {"title": "Enable network logging for security investigation", "rationale": "Network logs support incident investigation.", "recommendation": "Enable NSG flow logs and network diagnostic settings."},
    "MCSB:NS-1": {"title": "Establish network segmentation boundaries", "rationale": "Network segmentation limits lateral movement.", "recommendation": "Configure NSGs, private endpoints, and service endpoints."},
    "MCSB:NS-2": {"title": "Secure cloud services with network controls", "rationale": "Cloud services must be protected by network-level controls.", "recommendation": "Use private endpoints and restrict public access."},
    "MCSB:NS-3": {"title": "Deploy firewall at the edge", "rationale": "Edge firewalls protect against external threats.", "recommendation": "Deploy Azure Firewall or third-party NVA at the edge."},
    "MCSB:PA-1": {"title": "Protect and limit highly privileged users", "rationale": "Highly privileged users represent the highest-value targets.", "recommendation": "Limit Global Admins and enable PIM."},
    "MCSB:PA-4": {"title": "Review and reconcile user access regularly", "rationale": "Regular access reviews prevent accumulation of excess permissions.", "recommendation": "Configure periodic access reviews for all user types."},
    "MCSB:PA-7": {"title": "Follow least privileged administration principle", "rationale": "Least privilege reduces the impact of compromised accounts.", "recommendation": "Review and minimize RBAC assignments."},
    "MCSB:PV-5": {"title": "Perform vulnerability assessments", "rationale": "Regular vulnerability assessments identify exploitable weaknesses.", "recommendation": "Enable Defender vulnerability assessments."},
    "MCSB:PV-6": {"title": "Rapidly and automatically remediate vulnerabilities", "rationale": "Automated remediation accelerates vulnerability closure.", "recommendation": "Use Azure Policy DeployIfNotExists for auto-remediation."},

    # ── CSA-CCM v4 ───────────────────────────────────────────────────────
    "CSA-CCM:CEK-03": {"title": "Data Encryption", "rationale": "Data must be encrypted in transit to prevent interception.", "recommendation": "Enforce TLS 1.2+ on all endpoints."},
    "CSA-CCM:DSP-01": {"title": "Data Security Policy", "rationale": "Data governance policies must be defined and enforced.", "recommendation": "Implement tagging and classification policies."},
    "CSA-CCM:DSP-10": {"title": "Data Protection Network Access", "rationale": "Network access to data must be controlled.", "recommendation": "Use private endpoints and NSGs for data resources."},
    "CSA-CCM:DSP-17": {"title": "Encryption of Data in Transit", "rationale": "Data in transit must use strong encryption.", "recommendation": "Enforce TLS 1.2+ on all communication channels."},
    "CSA-CCM:GRC-01": {"title": "Information Security Program", "rationale": "An information security program must be established.", "recommendation": "Use Defender secure score as a security program metric."},
    "CSA-CCM:GRC-02": {"title": "Risk Management Program", "rationale": "Risks must be identified, assessed, and managed.", "recommendation": "Leverage Defender recommendations for risk management."},
    "CSA-CCM:GRC-03": {"title": "Organizational Policy", "rationale": "Security policies must be documented and enforced.", "recommendation": "Enforce Azure Policy aligned to organizational standards."},
    "CSA-CCM:HRS-09": {"title": "Personnel Screening", "rationale": "Personnel activities must be monitored for insider risk.", "recommendation": "Deploy Insider Risk Management."},
    "CSA-CCM:IAM-02": {"title": "Strong Authentication", "rationale": "Strong authentication mechanisms must be enforced.", "recommendation": "Enforce MFA for all users."},
    "CSA-CCM:IAM-04": {"title": "Policies and Procedures", "rationale": "IAM policies must be documented and followed.", "recommendation": "Document and enforce access management procedures."},
    "CSA-CCM:IAM-05": {"title": "Segregation of Duties", "rationale": "Segregation of duties prevents conflicts of interest.", "recommendation": "Separate admin roles and enforce separation of duties."},
    "CSA-CCM:IAM-06": {"title": "User Access Provisioning", "rationale": "User access must be provisioned and deprovisioned in a timely manner.", "recommendation": "Implement automated provisioning and access reviews."},
    "CSA-CCM:IAM-09": {"title": "Credential Lifecycle Management", "rationale": "Credentials must be managed through their lifecycle.", "recommendation": "Set credential expiry and rotate regularly."},
    "CSA-CCM:IAM-10": {"title": "Privileged Access Management", "rationale": "Privileged access must be restricted and monitored.", "recommendation": "Use PIM and limit standing privileged assignments."},
    "CSA-CCM:IAM-12": {"title": "User Access Review", "rationale": "User access must be reviewed regularly.", "recommendation": "Configure periodic access reviews for all user types."},
    "CSA-CCM:IVS-03": {"title": "Network Security", "rationale": "Network security controls must be deployed.", "recommendation": "Implement NSGs, firewalls, and private endpoints."},
    "CSA-CCM:IVS-06": {"title": "Network Security Management", "rationale": "Network security must be continuously managed.", "recommendation": "Monitor NSG rules and firewall configurations."},
    "CSA-CCM:LOG-01": {"title": "Logging and Monitoring", "rationale": "Logging must be enabled for all critical resources.", "recommendation": "Enable diagnostic settings on all resources."},
    "CSA-CCM:LOG-03": {"title": "Security Monitoring and Alerting", "rationale": "Security events must be monitored and alerted.", "recommendation": "Configure alerts for security events in Azure Monitor."},
    "CSA-CCM:TVM-01": {"title": "Threat and Vulnerability Management", "rationale": "Threats and vulnerabilities must be identified and managed.", "recommendation": "Enable Defender for Cloud and address recommendations."},
    "CSA-CCM:TVM-02": {"title": "Vulnerability Management", "rationale": "Vulnerabilities must be prioritized and remediated.", "recommendation": "Address high-severity Defender recommendations promptly."},
}


def enrich_compliance_mapping(findings: list[dict]) -> list[dict]:
    """Add ComplianceMapping and ComplianceDetails to each risk finding."""
    for f in findings:
        subcat = f.get("Subcategory", "")
        mapping = _COMPLIANCE_MAP.get(subcat)
        if mapping:
            f["ComplianceMapping"] = mapping
            details: dict[str, dict[str, str]] = {}
            for fw, ctrls in mapping.items():
                for ctrl in ctrls:
                    key = f"{fw}:{ctrl}"
                    if key in _CONTROL_DETAILS:
                        details[key] = _CONTROL_DETAILS[key]
            if details:
                f["ComplianceDetails"] = details
    return findings
