"""
Drift Report — HTML
Compares current vs previous assessment run and generates ``drift-report.html``.
Shows: new findings, resolved findings, regression findings, score trend.
"""

from __future__ import annotations
import pathlib
from typing import Any
from app.logger import log
from app.postureiq_reports.shared_theme import get_css, get_js, esc, severity_badge, status_badge


def generate_drift_report_html(
    delta: dict[str, Any] | None,
    results: dict[str, Any],
    tenant_info: dict[str, Any],
    output_dir: str,
) -> str:
    """Generate ``drift-report.html`` showing differences from the previous run.

    Returns path to the generated file.
    """
    out = pathlib.Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "drift-report.html"

    tenant = esc(tenant_info.get("display_name", tenant_info.get("tenant_id", "")))
    summary = results.get("summary", {})
    score = summary.get("ComplianceScore", 0)

    # Build sections
    score_section = _score_change_section(delta)
    status_section = _status_change_section(delta)
    new_section = _findings_section("New Findings", delta.get("new_findings", []) if delta else [], "new")
    resolved_section = _findings_section("Resolved Findings", delta.get("resolved_findings", []) if delta else [], "resolved")

    html = f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Drift Report — {tenant}</title>
<style>{get_css()}</style>
</head>
<body>
<a href="#main-content" class="skip-nav">Skip to content</a>
<main class="content" id="main-content" style="max-width:1200px;margin:0 auto;padding:2rem">
<header style="text-align:center;margin-bottom:2rem">
  <h1>Compliance Drift Report</h1>
  <p class="subtitle">Tenant: {tenant} &nbsp;|&nbsp; Current Score: <strong>{score:.1f}%</strong></p>
  <p class="dim">{esc(delta.get('summary', 'No previous run available for comparison.') if delta else 'No previous run available for comparison.')}</p>
</header>

{score_section}
{status_section}
{new_section}
{resolved_section}

<footer style="text-align:center;padding:2rem 0;opacity:.5;font-size:.85rem">
  Generated by PostureIQ
</footer>
</main>
<script>{get_js()}</script>
</body>
</html>"""

    path.write_text(html, encoding="utf-8")
    log.info("Drift report → %s", path)
    return str(path)


def _score_change_section(delta: dict | None) -> str:
    if not delta or not delta.get("score_change"):
        return '<section><h2>Score Changes</h2><p class="dim">No score comparison available.</p></section>'

    rows = ""
    for fw, sc in delta["score_change"].items():
        d = sc.get("delta", 0)
        color = "var(--success)" if d > 0 else ("var(--danger)" if d < 0 else "var(--text-dim)")
        sign = "+" if d > 0 else ""
        rows += f"""<tr>
  <td>{esc(fw)}</td>
  <td>{sc.get('old', 0):.1f}%</td>
  <td>{sc.get('new', 0):.1f}%</td>
  <td style="color:{color};font-weight:600">{sign}{d:.1f}%</td>
</tr>"""

    return f"""<section>
<h2>Score Changes</h2>
<table class="data-table"><thead><tr>
  <th>Framework</th><th>Previous</th><th>Current</th><th>Change</th>
</tr></thead><tbody>{rows}</tbody></table>
</section>"""


def _status_change_section(delta: dict | None) -> str:
    changes = delta.get("status_changes", []) if delta else []
    if not changes:
        return '<section><h2>Control Status Changes</h2><p class="dim">No status changes detected.</p></section>'

    improved = [c for c in changes if c.get("new_status") in ("compliant", "COMPLIANT")]
    regressed = [c for c in changes if c.get("old_status") in ("compliant", "COMPLIANT") and c.get("new_status") not in ("compliant", "COMPLIANT")]
    other = [c for c in changes if c not in improved and c not in regressed]

    rows = ""
    for c in regressed + other + improved:
        rows += f"""<tr>
  <td>{esc(c.get('control_id', ''))}</td>
  <td>{esc(c.get('title', ''))}</td>
  <td>{status_badge(c.get('old_status', ''))}</td>
  <td>{status_badge(c.get('new_status', ''))}</td>
</tr>"""

    return f"""<section>
<h2>Control Status Changes</h2>
<p><strong>{len(improved)}</strong> improved &nbsp;|&nbsp; <strong>{len(regressed)}</strong> regressed &nbsp;|&nbsp; <strong>{len(other)}</strong> other</p>
<table class="data-table"><thead><tr>
  <th>Control</th><th>Title</th><th>Previous</th><th>Current</th>
</tr></thead><tbody>{rows}</tbody></table>
</section>"""


def _findings_section(title: str, findings: list[dict], cls: str) -> str:
    if not findings:
        return f'<section><h2>{title}</h2><p class="dim">None.</p></section>'

    color = "var(--danger)" if cls == "new" else "var(--success)"
    rows = ""
    for f in findings[:50]:
        rows += f"""<tr>
  <td>{esc(f.get('ControlId', f.get('control_id', '')))}</td>
  <td>{severity_badge(f.get('Severity', f.get('severity', 'medium')))}</td>
  <td>{esc(f.get('Description', f.get('detail', '')))[:120]}</td>
</tr>"""

    return f"""<section>
<h2 style="color:{color}">{title} ({len(findings)})</h2>
<table class="data-table"><thead><tr>
  <th>Control</th><th>Severity</th><th>Detail</th>
</tr></thead><tbody>{rows}</tbody></table>
</section>"""
