"""M365 Copilot security controls matrix builder."""

from __future__ import annotations

from .finding import _SEVERITY_WEIGHTS


# MS Reference label → Microsoft Learn documentation URL
_MS_REFERENCE_URLS: dict[str, str] = {
    "MS Copilot Readiness — Oversharing Assessment": "https://learn.microsoft.com/microsoft-365/admin/copilot/microsoft-365-copilot-privacy",
    "MS Copilot Readiness — Permission Cleanup": "https://learn.microsoft.com/sharepoint/site-permissions",
    "MS Copilot Readiness — Sharing Controls": "https://learn.microsoft.com/sharepoint/turn-external-sharing-on-or-off",
    "MS Copilot Readiness — External Sharing": "https://learn.microsoft.com/sharepoint/external-sharing-overview",
    "MS Copilot Readiness — Least Privilege": "https://learn.microsoft.com/microsoft-365/admin/copilot/microsoft-365-copilot-privacy",
    "MS SharePoint — Advanced Management": "https://learn.microsoft.com/sharepoint/advanced-management",
    "MS SharePoint — SAM Restricted Access": "https://learn.microsoft.com/sharepoint/restricted-access-control",
    "MS SharePoint — SAM Site Lifecycle": "https://learn.microsoft.com/sharepoint/site-lifecycle-management",
    "MS SharePoint — SAM DAG Reports": "https://learn.microsoft.com/sharepoint/data-access-governance",
    "MS Purview — Information Protection": "https://learn.microsoft.com/purview/information-protection",
    "MS Purview — Label Policies": "https://learn.microsoft.com/purview/sensitivity-labels",
    "MS Purview — Auto-Labeling": "https://learn.microsoft.com/purview/apply-sensitivity-label-automatically",
    "MS Purview — Container Labels": "https://learn.microsoft.com/purview/sensitivity-labels-teams-groups-sites",
    "MS Purview — Default Labels": "https://learn.microsoft.com/purview/sensitivity-labels-office-apps",
    "MS Purview — DLP": "https://learn.microsoft.com/purview/dlp-learn-about-dlp",
    "MS Purview — DLP Label Conditions": "https://learn.microsoft.com/purview/dlp-conditions-and-exceptions",
    "MS Purview — DLP Locations": "https://learn.microsoft.com/purview/dlp-policy-reference",
    "MS Purview — Endpoint DLP": "https://learn.microsoft.com/purview/endpoint-dlp-learn-about",
    "MS SharePoint — Restricted Search": "https://learn.microsoft.com/sharepoint/restricted-sharepoint-search",
    "MS Entra — Conditional Access": "https://learn.microsoft.com/entra/identity/conditional-access/overview",
    "MS Admin — License Management": "https://learn.microsoft.com/microsoft-365/admin/manage/assign-licenses-to-users",
    "MS Admin — Licensing": "https://learn.microsoft.com/microsoft-365/admin/manage/assign-licenses-to-users",
    "MS Entra — Identity Governance": "https://learn.microsoft.com/entra/id-governance/access-reviews-overview",
    "MS Purview — Information Barriers": "https://learn.microsoft.com/purview/information-barriers",
    "MS Entra — Authentication Methods": "https://learn.microsoft.com/entra/identity/authentication/concept-authentication-methods",
    "MS Entra — PIM": "https://learn.microsoft.com/entra/id-governance/privileged-identity-management/pim-configure",
    "MS Entra — Named Locations": "https://learn.microsoft.com/entra/identity/conditional-access/location-condition",
    "MS Entra — Identity Protection": "https://learn.microsoft.com/entra/id-protection/overview-identity-protection",
    "MS Intune — Device Compliance": "https://learn.microsoft.com/mem/intune/protect/device-compliance-get-started",
    "MS SharePoint — Site Lifecycle": "https://learn.microsoft.com/sharepoint/site-lifecycle-management",
    "MS Purview — Retention": "https://learn.microsoft.com/purview/retention-policies-sharepoint",
    "MS Admin — M365 Backup": "https://learn.microsoft.com/microsoft-365/backup/backup-overview",
    "MS Purview — Audit": "https://learn.microsoft.com/purview/audit-log-enable-disable",
    "MS Purview — Copilot Audit Events": "https://learn.microsoft.com/purview/audit-copilot",
    "MS Purview — Alert Policies": "https://learn.microsoft.com/purview/alert-policies",
    "MS Defender — Cloud Apps": "https://learn.microsoft.com/defender-cloud-apps/what-is-defender-for-cloud-apps",
    "MS Admin — Copilot Settings": "https://learn.microsoft.com/microsoft-365/admin/copilot/manage-plugins",
    "MS Trust Center — Data Residency": "https://learn.microsoft.com/microsoft-365/enterprise/m365-dr-overview",
    "MS Purview — eDiscovery": "https://learn.microsoft.com/purview/ediscovery",
    "MS Copilot Readiness — Graph Grounding": "https://learn.microsoft.com/microsoft-365/admin/copilot/microsoft-365-copilot-privacy",
    "MS Purview — Insider Risk": "https://learn.microsoft.com/purview/insider-risk-management",
    "MS Purview — Communication Compliance": "https://learn.microsoft.com/purview/communication-compliance",
    "MS Purview — DSPM for AI": "https://learn.microsoft.com/purview/ai-microsoft-purview-considerations",
    "MS Purview — DSPM Oversharing": "https://learn.microsoft.com/purview/ai-microsoft-purview-considerations",
    # Phase 1-4 enhancement references
    "MS Entra — User Sign-In Activity": "https://learn.microsoft.com/entra/identity/monitoring-health/concept-sign-ins",
    "MS Entra — Global Admin Best Practices": "https://learn.microsoft.com/entra/identity/role-based-access-control/best-practices",
    "MS Entra — Shared Accounts": "https://learn.microsoft.com/entra/identity/enterprise-apps/secure-shared-accounts",
    "MS Entra — Group-Based Licensing": "https://learn.microsoft.com/entra/identity/users/licensing-groups-resolve-problems",
    "MS Entra — Session Controls": "https://learn.microsoft.com/entra/identity/conditional-access/howto-conditional-access-session-lifetime",
    "MS Purview — Legal Hold": "https://learn.microsoft.com/purview/ediscovery-create-a-litigation-hold",
    "MS Exchange — Mailbox Permissions": "https://learn.microsoft.com/exchange/recipients-in-exchange-online/manage-permissions-for-recipients",
    "MS Exchange — Shared Mailboxes": "https://learn.microsoft.com/microsoft-365/admin/email/about-shared-mailboxes",
    "MS Copilot Studio — Agent Governance": "https://learn.microsoft.com/microsoft-copilot-studio/admin-governance",
    "MS Entra — App Permissions": "https://learn.microsoft.com/entra/identity/enterprise-apps/manage-application-permissions",
    "MS Purview — IB Segments": "https://learn.microsoft.com/purview/information-barriers-policies",
    "MS Purview — Label Policy Scope": "https://learn.microsoft.com/purview/sensitivity-labels-office-apps",
    "MS Purview — Compliance Manager": "https://learn.microsoft.com/purview/compliance-manager",
    "MS Trust Center — Multi-Geo": "https://learn.microsoft.com/microsoft-365/enterprise/microsoft-365-multi-geo",
    "MS Admin — Copilot License Offboarding": "https://learn.microsoft.com/microsoft-365/admin/manage/remove-licenses-from-users",
    "MS Responsible AI": "https://learn.microsoft.com/ai/responsible-ai-overview",
    "MS Admin — Copilot Usage Reports": "https://learn.microsoft.com/microsoft-365/admin/activity-reports/microsoft-365-copilot-usage",
    "MS Purview — Copilot Audit Events": "https://learn.microsoft.com/purview/audit-copilot",
    "MS Purview — Prompt Monitoring": "https://learn.microsoft.com/purview/communication-compliance",
    "MS SharePoint — Blast Radius": "https://learn.microsoft.com/sharepoint/site-permissions",
    "MS SharePoint — External Sharing Governance": "https://learn.microsoft.com/sharepoint/external-sharing-overview",
    "MS Intune — App Protection Policies": "https://learn.microsoft.com/mem/intune/apps/app-protection-policy",
    "MS Purview — Label Encryption": "https://learn.microsoft.com/purview/encryption-sensitivity-labels",
    "MS Purview — Label Site & Group Settings": "https://learn.microsoft.com/purview/sensitivity-labels-teams-groups-sites",
    "MS SharePoint — Restricted Content Discoverability": "https://learn.microsoft.com/sharepoint/restricted-content-discoverability",
    # Phase 6: Checklist Gap Closure
    "MS Entra — Cross-Tenant Access": "https://learn.microsoft.com/entra/external-id/cross-tenant-access-overview",
    "MS Entra — Hybrid Identity": "https://learn.microsoft.com/entra/identity/hybrid/whatis-hybrid-identity",
    "MS Admin — Copilot License Segmentation": "https://learn.microsoft.com/microsoft-365/admin/manage/assign-licenses-to-users",
    "MS Copilot — Agent Approval": "https://learn.microsoft.com/microsoft-365-copilot/extensibility/manage-agents-copilot",
    "MS Graph — External Connectors": "https://learn.microsoft.com/microsoftsearch/connectors-overview",
    "MS Defender — Copilot Incidents": "https://learn.microsoft.com/defender/investigate-incidents",
    "MS Copilot — Prompt Guardrails": "https://learn.microsoft.com/microsoft-365-copilot/microsoft-365-copilot-privacy",
}

# Remediation effort estimate per finding subcategory
# quick_win: admin portal config change (<1 hour)
# moderate: planning + implementation (1 day – 1 week)
# major: organizational rollout, licensing, or complex deployment (>1 week)
_EFFORT_MAP: dict[str, str] = {
    "unable_to_assess": "quick_win",
    "partial_site_discovery": "quick_win",
    "everyone_permissions": "quick_win",
    "anonymous_link_exposure": "quick_win",
    "external_sharing_open": "quick_win",
    "broad_site_membership": "moderate",
    "no_sam_license": "moderate",
    "no_sam_restricted_access_control": "moderate",
    "no_sam_site_lifecycle_policy": "quick_win",
    "no_sam_dag_reports": "quick_win",
    "no_labels_defined": "major",
    "no_mandatory_labeling": "quick_win",
    "no_auto_labeling": "moderate",
    "low_site_label_coverage": "moderate",
    "no_default_label": "quick_win",
    "mandatory_labeling_incomplete_scope": "moderate",
    "no_dlp_policies": "major",
    "no_dlp_label_conditions": "moderate",
    "dlp_workload_gaps": "moderate",
    "no_endpoint_dlp": "moderate",
    "rss_not_configured": "quick_win",
    "no_ca_policy_for_copilot": "moderate",
    "copilot_license_not_scoped": "quick_win",
    "no_copilot_license": "major",
    "copilot_licenses_unassigned": "quick_win",
    "low_copilot_license_utilization": "quick_win",
    "no_access_reviews": "moderate",
    "no_information_barriers": "major",
    "no_mfa_enforcement": "moderate",
    "no_pim_configured": "moderate",
    "no_named_locations": "quick_win",
    "no_signin_risk_policy": "moderate",
    "no_device_compliance": "major",
    # Phase 1: Identity & Licensing
    "stale_accounts_detected": "moderate",
    "excessive_global_admins": "moderate",
    "shared_accounts_detected": "moderate",
    "no_group_based_licensing": "quick_win",
    "no_session_signin_frequency": "quick_win",
    "no_persistent_browser_control": "quick_win",
    # Phase 2: Exchange & Agent Governance
    "mailbox_delegation_fullaccess": "moderate",
    "shared_mailbox_over_delegated": "moderate",
    "ib_segments_not_assigned": "moderate",
    "disabled_users_with_copilot_license": "quick_win",
    "unmanaged_copilot_agents": "moderate",
    "agent_over_permissioned": "moderate",
    # Content Lifecycle
    "stale_content_exposure": "moderate",
    "retention_assessment_needed": "moderate",
    "no_m365_backup": "moderate",
    "no_legal_hold_configured": "moderate",
    # Audit & Monitoring
    "audit_logging_unknown": "quick_win",
    "copilot_interaction_audit": "quick_win",
    "no_alert_policies": "moderate",
    "no_defender_cloud_apps": "major",
    "no_copilot_usage_analytics": "quick_win",
    "copilot_audit_events_not_analyzed": "moderate",
    "no_prompt_pattern_monitoring": "moderate",
    # Copilot-Specific Security
    "copilot_plugins_unrestricted": "quick_win",
    "data_residency_unverified": "quick_win",
    "no_ediscovery_configured": "moderate",
    "no_insider_risk_policies": "major",
    "no_communication_compliance": "major",
    "no_dspm_for_ai": "moderate",
    "dspm_oversharing_not_reviewed": "quick_win",
    "no_regulatory_framework_mapping": "moderate",
    "multi_geo_copilot_residency": "moderate",
    "no_rai_policy": "moderate",
    # Phase 4: Advanced Security
    "high_permission_blast_radius": "moderate",
    "external_sharing_risk_score": "moderate",
    # Phase 5: App Protection, Label Encryption, RCD
    "no_app_protection_policies": "moderate",
    "app_protection_platform_gaps": "moderate",
    "labels_without_encryption": "moderate",
    "labels_without_site_group_settings": "quick_win",
    "rcd_not_configured": "quick_win",
    # Phase 6: Checklist Gap Closure
    "cross_tenant_access_not_assessed": "moderate",
    "cross_tenant_access_permissive": "moderate",
    "hybrid_accounts_stale_sync": "moderate",
    "no_copilot_license_segmentation": "quick_win",
    "no_agent_approval_workflow": "moderate",
    "ungoverned_external_connectors": "moderate",
    "external_connector_review_needed": "quick_win",
    "copilot_security_incidents_detected": "major",
    "no_prompt_guardrails": "quick_win",
    # Zero Trust
    "no_continuous_access_evaluation": "moderate",
    "no_token_protection": "moderate",
    "no_phishing_resistant_mfa": "moderate",
    "no_authentication_context": "moderate",
    "workload_identity_unprotected": "moderate",
    "no_compliant_network_check": "moderate",
    # Shadow AI
    "unauthorized_ai_apps_detected": "major",
    "ai_consent_grants_detected": "moderate",
    "shadow_copilot_agents_detected": "moderate",
    "no_ai_app_governance": "moderate",
    "ai_apps_overpermissioned": "moderate",
    "no_ai_dlp_web_restrictions": "moderate",
}

# Each control: (id, name, category, description, mapped_subcategories, microsoft_ref)
# mapped_subcategories: finding subcategories that indicate a FAILURE for this control.
# If empty, the control is advisory-only (NOT_ASSESSED unless manually verified).
_COPILOT_SECURITY_CONTROLS: list[tuple[str, str, str, str, list[str], str]] = [
    # ── Oversharing Risk ──
    ("CTRL-OVR-001", "SharePoint Site Permissions Audit",
     "oversharing_risk",
     "Audit permissions on all SharePoint sites to identify overly broad access before Copilot indexes content.",
     ["unable_to_assess", "partial_site_discovery"],
     "MS Copilot Readiness — Oversharing Assessment"),
    ("CTRL-OVR-002", "Remove 'Everyone' Group Access",
     "oversharing_risk",
     "Remove 'Everyone' and 'Everyone except external users' from SharePoint site permissions.",
     ["everyone_permissions"],
     "MS Copilot Readiness — Permission Cleanup"),
    ("CTRL-OVR-003", "Eliminate Anonymous Sharing Links",
     "oversharing_risk",
     "Remove or convert anonymous sharing links that bypass identity checks.",
     ["anonymous_link_exposure"],
     "MS Copilot Readiness — Sharing Controls"),
    ("CTRL-OVR-004", "Restrict External Sharing",
     "oversharing_risk",
     "Set tenant external sharing to 'Existing guests' or lower to prevent uncontrolled data exposure.",
     ["external_sharing_posture"],
     "MS Copilot Readiness — External Sharing"),
    ("CTRL-OVR-005", "Remediate Broad Site Membership",
     "oversharing_risk",
     "Review and reduce membership on sites with 100+ permission entries.",
     ["broad_site_membership"],
     "MS Copilot Readiness — Least Privilege"),
    ("CTRL-OVR-006", "SharePoint Advanced Management",
     "oversharing_risk",
     "Enable SharePoint Advanced Management (SAM) for Data Access Governance reports and site lifecycle management.",
     ["no_sharepoint_advanced_management"],
     "MS SharePoint — Advanced Management"),
    ("CTRL-OVR-007", "SAM Restricted Access Control",
     "oversharing_risk",
     "Configure SAM Restricted Access Control to limit sensitive site access to specific security groups.",
     ["no_sam_restricted_access_control"],
     "MS SharePoint — SAM Restricted Access"),
    ("CTRL-OVR-008", "SAM Site Lifecycle Policy",
     "oversharing_risk",
     "Enable SAM site lifecycle policies to detect and manage inactive sites before Copilot indexes stale content.",
     ["no_sam_site_lifecycle_policy"],
     "MS SharePoint — SAM Site Lifecycle"),
    ("CTRL-OVR-009", "SAM Data Access Governance Reports",
     "oversharing_risk",
     "Generate SAM Data Access Governance reports to identify overshared sites and sensitive content locations.",
     ["no_sam_dag_reports"],
     "MS SharePoint — SAM DAG Reports"),

    # ── Sensitivity Label Coverage ──
    ("CTRL-LBL-001", "Define Sensitivity Label Taxonomy",
     "label_coverage",
     "Create at minimum: Public, Internal, Confidential, Highly Confidential sensitivity labels.",
     ["no_labels_defined", "insufficient_labels", "label_api_inaccessible"],
     "MS Purview — Information Protection"),
    ("CTRL-LBL-002", "Enforce Mandatory Labeling",
     "label_coverage",
     "Require users to apply a sensitivity label to all documents and emails.",
     ["no_mandatory_labeling"],
     "MS Purview — Label Policies"),
    ("CTRL-LBL-003", "Configure Auto-Labeling",
     "label_coverage",
     "Configure auto-labeling policies for sensitive information types (PII, financial, health data).",
     ["no_auto_labeling"],
     "MS Purview — Auto-Labeling"),
    ("CTRL-LBL-004", "Apply Site-Level Sensitivity Labels",
     "label_coverage",
     "Apply sensitivity labels to all SharePoint sites so Copilot respects container-level protections.",
     ["low_site_label_coverage"],
     "MS Purview — Container Labels"),
    ("CTRL-LBL-005", "Configure Default Sensitivity Label",
     "label_coverage",
     "Set a default sensitivity label in label policies so new content is automatically classified.",
     ["no_default_label"],
     "MS Purview — Default Labels"),

    # ── Data Loss Prevention ──
    ("CTRL-DLP-001", "Deploy DLP Policies",
     "dlp_readiness",
     "Create Data Loss Prevention policies to protect sensitive data in Copilot interactions.",
     ["no_dlp_policies"],
     "MS Purview — DLP"),
    ("CTRL-DLP-002", "Add Label-Based DLP Rules",
     "dlp_readiness",
     "Configure DLP rules that trigger on sensitivity labels for label-aware Copilot protection.",
     ["no_label_based_dlp"],
     "MS Purview — DLP Label Conditions"),
    ("CTRL-DLP-003", "DLP Workload Coverage",
     "dlp_readiness",
     "Ensure DLP policies cover Exchange, SharePoint, OneDrive, and Teams workloads.",
     ["incomplete_workload_coverage"],
     "MS Purview — DLP Locations"),
    ("CTRL-DLP-004", "Endpoint DLP for Copilot",
     "dlp_readiness",
     "Enable Endpoint DLP to monitor Copilot-generated content copied to local devices.",
     ["no_endpoint_dlp"],
     "MS Purview — Endpoint DLP"),

    # ── Restricted SharePoint Search ──
    ("CTRL-RSS-001", "Configure Restricted SharePoint Search",
     "restricted_search",
     "Enable RSS to limit which SharePoint sites Copilot can index and surface content from.",
     ["rss_not_configured"],
     "MS SharePoint — Restricted Search"),

    # ── Access Governance ──
    ("CTRL-GOV-001", "Conditional Access for Copilot",
     "access_governance",
     "Create Conditional Access policies targeting M365 Copilot (device compliance, MFA, location).",
     ["ca_unable_to_assess", "no_copilot_ca_policy"],
     "MS Entra — Conditional Access"),
    ("CTRL-GOV-002", "Scoped Copilot Deployment",
     "access_governance",
     "Deploy Copilot to a pilot group first using group-based licensing before org-wide rollout.",
     ["copilot_deployment_scope_denied", "copilot_deployment_unknown"],
     "MS Admin — License Management"),
    ("CTRL-GOV-003", "M365 Copilot Licensing",
     "access_governance",
     "Ensure the tenant has active Microsoft 365 Copilot licenses assigned.",
     ["no_copilot_license"],
     "MS Admin — Licensing"),
    ("CTRL-GOV-003a", "Copilot License Assignment",
     "access_governance",
     "Verify Copilot licenses are assigned to users — purchased licenses must be assigned to be effective.",
     ["copilot_licenses_unassigned", "low_copilot_license_utilization"],
     "MS Admin — License Management"),
    ("CTRL-GOV-004", "Entra Access Reviews",
     "access_governance",
     "Configure recurring access reviews to prevent permission sprawl that exposes data via Copilot.",
     ["no_access_reviews"],
     "MS Entra — Identity Governance"),
    ("CTRL-GOV-005", "Information Barriers",
     "access_governance",
     "Configure information barriers to prevent Copilot from surfacing content across compliance boundaries.",
     ["no_information_barriers"],
     "MS Purview — Information Barriers"),
    ("CTRL-GOV-006", "MFA Enforcement for Copilot Users",
     "access_governance",
     "Enforce multi-factor authentication for all users with M365 Copilot access to prevent credential-based attacks.",
     ["no_mfa_enforcement"],
     "MS Entra — Authentication Methods"),
    ("CTRL-GOV-007", "Privileged Identity Management",
     "access_governance",
     "Enable PIM for just-in-time elevation of admin roles that can change Copilot settings and data access policies.",
     ["no_pim_configured"],
     "MS Entra — PIM"),
    ("CTRL-GOV-008", "Named Locations for Conditional Access",
     "access_governance",
     "Define trusted network locations so Conditional Access policies can restrict Copilot access by location.",
     ["no_named_locations"],
     "MS Entra — Named Locations"),
    ("CTRL-GOV-009", "Sign-in Risk Policy",
     "access_governance",
     "Configure Identity Protection sign-in risk policies to block or challenge risky authentications to Copilot.",
     ["no_signin_risk_policy"],
     "MS Entra — Identity Protection"),
    ("CTRL-GOV-010", "Device Compliance for Copilot",
     "access_governance",
     "Require Intune device compliance for Copilot access to ensure data stays on managed, encrypted devices.",
     ["no_device_compliance"],
     "MS Intune — Device Compliance"),

    # ── Content Lifecycle ──
    ("CTRL-CLM-001", "Remediate Stale Content",
     "content_lifecycle",
     "Archive or delete stale SharePoint sites to prevent Copilot from indexing outdated information.",
     ["stale_content_exposure"],
     "MS SharePoint — Site Lifecycle"),
    ("CTRL-CLM-002", "Retention Policies for Copilot",
     "content_lifecycle",
     "Configure retention policies covering Teams chats and Copilot-generated content.",
     ["retention_assessment_needed"],
     "MS Purview — Retention"),
    ("CTRL-CLM-003", "Microsoft 365 Backup",
     "content_lifecycle",
     "Enable Microsoft 365 Backup for rapid recovery of Exchange, OneDrive, and SharePoint content.",
     ["no_m365_backup"],
     "MS Admin — M365 Backup"),

    # ── Audit & Monitoring ──
    ("CTRL-AUD-001", "Enable Unified Audit Logging",
     "audit_monitoring",
     "Enable unified audit logging to track all M365 Copilot interactions and content access.",
     ["audit_logging_unknown"],
     "MS Purview — Audit"),
    ("CTRL-AUD-002", "Copilot Interaction Audit Events",
     "audit_monitoring",
     "Verify CopilotInteraction audit events are captured and monitored.",
     ["copilot_interaction_audit"],
     "MS Purview — Copilot Audit Events"),
    ("CTRL-AUD-003", "Alert Policies for Copilot",
     "audit_monitoring",
     "Create alert policies for sensitive content access and anomalous Copilot activity.",
     ["no_alert_policies"],
     "MS Purview — Alert Policies"),
    ("CTRL-AUD-004", "Microsoft Defender for Cloud Apps",
     "audit_monitoring",
     "Enable Defender for Cloud Apps session monitoring to detect and block risky Copilot data transfers in real time.",
     ["no_defender_cloud_apps"],
     "MS Defender — Cloud Apps"),

    # ── Copilot-Specific Security (additional Microsoft-recommended controls) ──
    ("CTRL-CPS-001", "Copilot Plugin & Connector Restrictions",
     "copilot_security",
     "Restrict which Copilot plugins and connectors are available to prevent data exfiltration via third-party integrations.",
     ["copilot_plugins_unrestricted"],
     "MS Admin — Copilot Settings"),
    ("CTRL-CPS-002", "Copilot Data Residency Compliance",
     "copilot_security",
     "Verify that Copilot data processing complies with your organization's data residency requirements.",
     ["data_residency_unverified"],
     "MS Trust Center — Data Residency"),
    ("CTRL-CPS-003", "eDiscovery for Copilot Interactions",
     "copilot_security",
     "Ensure eDiscovery and Content Search can locate and preserve Copilot interaction data.",
     ["no_ediscovery_configured"],
     "MS Purview — eDiscovery"),
    ("CTRL-CPS-004", "Semantic Index & Graph Grounding Scope",
     "copilot_security",
     "Review Microsoft Graph grounding scope — Copilot surfaces content the user has access to via Graph.",
     [],  # Advisory — inherent to Copilot architecture
     "MS Copilot Readiness — Graph Grounding"),
    ("CTRL-CPS-005", "Insider Risk Management for Copilot",
     "copilot_security",
     "Configure Insider Risk Management policies to detect anomalous Copilot usage patterns.",
     ["no_insider_risk_policies"],
     "MS Purview — Insider Risk"),
    ("CTRL-CPS-006", "Communication Compliance for Copilot",
     "copilot_security",
     "Configure Communication Compliance policies to detect inappropriate or non-compliant content generated by Copilot.",
     ["no_communication_compliance"],
     "MS Purview — Communication Compliance"),
    ("CTRL-CPS-007", "DSPM for AI Enablement",
     "copilot_security",
     "Enable Data Security Posture Management (DSPM) for AI in Purview to monitor sensitive data risks in Copilot interactions.",
     ["no_dspm_for_ai"],
     "MS Purview — DSPM for AI"),
    ("CTRL-CPS-008", "DSPM Oversharing Assessment",
     "copilot_security",
     "Run DSPM oversharing assessments to identify sensitive content accessible to Copilot and prioritize remediation.",
     ["dspm_oversharing_not_reviewed"],
     "MS Purview — DSPM Oversharing"),

    # ── Phase 1: Identity & Licensing Enhancements ──
    ("CTRL-GOV-011", "Stale Account Detection",
     "access_governance",
     "Detect and remediate user accounts with no sign-in for 90+ days that retain Copilot data access.",
     ["stale_accounts_detected"],
     "MS Entra — User Sign-In Activity"),
    ("CTRL-GOV-012", "Global Administrator Count",
     "access_governance",
     "Ensure no more than 5 standing Global Administrators to limit blast radius on Copilot configuration.",
     ["excessive_global_admins"],
     "MS Entra — Global Admin Best Practices"),
    ("CTRL-GOV-013", "Shared Account Detection",
     "access_governance",
     "Detect shared/generic accounts that undermine individual accountability for Copilot activities.",
     ["shared_accounts_detected"],
     "MS Entra — Shared Accounts"),
    ("CTRL-GOV-014", "Group-Based Licensing for Copilot",
     "access_governance",
     "Verify Copilot licenses are assigned via security groups instead of direct assignment for governed rollout.",
     ["no_group_based_licensing"],
     "MS Entra — Group-Based Licensing"),
    ("CTRL-GOV-015", "Session Sign-In Frequency",
     "access_governance",
     "Enforce sign-in frequency controls via CA policies to prevent indefinite Copilot session persistence.",
     ["no_session_signin_frequency"],
     "MS Entra — Session Controls"),
    ("CTRL-GOV-016", "Persistent Browser Session Control",
     "access_governance",
     "Disable persistent browser sessions on unmanaged devices to prevent unattended Copilot access.",
     ["no_persistent_browser_control"],
     "MS Entra — Session Controls"),

    # ── Phase 2: Exchange & Agent Governance ──
    ("CTRL-GOV-017", "Mailbox Delegation Audit",
     "access_governance",
     "Audit Exchange mailbox delegations that silently expand a user's Copilot data surface.",
     ["mailbox_delegation_fullaccess"],
     "MS Exchange — Mailbox Permissions"),
    ("CTRL-GOV-018", "Shared Mailbox Permission Sprawl",
     "access_governance",
     "Detect shared mailboxes with excessive membership broadening Copilot exposure.",
     ["shared_mailbox_over_delegated"],
     "MS Exchange — Shared Mailboxes"),
    ("CTRL-CPS-009", "Copilot Agent Inventory",
     "copilot_security",
     "Maintain an inventory of all published Copilot Studio agents with assigned owners.",
     ["unmanaged_copilot_agents"],
     "MS Copilot Studio — Agent Governance"),
    ("CTRL-CPS-010", "Agent Permission Boundary",
     "copilot_security",
     "Ensure Copilot agents follow least-privilege principles with minimal API permissions.",
     ["agent_over_permissioned"],
     "MS Entra — App Permissions"),
    ("CTRL-GOV-019", "Information Barrier Segment Enforcement",
     "access_governance",
     "Verify IB segment assignments are applied to enforce compliance boundaries for Copilot.",
     ["ib_segments_not_assigned"],
     "MS Purview — IB Segments"),
    ("CTRL-LBL-006", "Mandatory Labeling Workload Scope",
     "label_coverage",
     "Ensure mandatory labeling is enforced across all M365 workloads, not just a subset.",
     ["mandatory_labeling_incomplete_scope"],
     "MS Purview — Label Policy Scope"),

    # ── Phase 3: Compliance & Regulatory ──
    ("CTRL-CPS-011", "Regulatory Framework Mapping",
     "copilot_security",
     "Map Copilot controls to regulatory frameworks (ISO, SOC, GDPR, HIPAA) via Compliance Manager.",
     ["no_regulatory_framework_mapping"],
     "MS Purview — Compliance Manager"),
    ("CTRL-CPS-012", "Multi-Geo Data Residency Compliance",
     "copilot_security",
     "Verify Copilot data processing respects Multi-Geo data residency boundaries.",
     ["multi_geo_copilot_residency"],
     "MS Trust Center — Multi-Geo"),
    ("CTRL-GOV-020", "Copilot License Offboarding",
     "access_governance",
     "Detect disabled users still holding Copilot licenses — wasted cost and security risk.",
     ["disabled_users_with_copilot_license"],
     "MS Admin — Copilot License Offboarding"),
    ("CTRL-CPS-013", "Responsible AI Policy",
     "copilot_security",
     "Establish Responsible AI policies and labels for Copilot governance and ethical use.",
     ["no_rai_policy"],
     "MS Responsible AI"),
    ("CTRL-AUD-005", "Copilot Usage Analytics",
     "audit_monitoring",
     "Monitor Copilot adoption and usage patterns via M365 admin center reports.",
     ["no_copilot_usage_analytics"],
     "MS Admin — Copilot Usage Reports"),

    # ── Phase 4: Advanced Security Operations ──
    ("CTRL-OVR-010", "Permission Blast Radius Assessment",
     "oversharing_risk",
     "Score sites by permission blast radius to prioritize Copilot-related remediation.",
     ["high_permission_blast_radius"],
     "MS SharePoint — Blast Radius"),
    ("CTRL-AUD-006", "Copilot Audit Event Analysis",
     "audit_monitoring",
     "Actively analyze CopilotInteraction audit events for sensitive data access patterns.",
     ["copilot_audit_events_not_analyzed"],
     "MS Purview — Copilot Audit Events"),
    ("CTRL-AUD-007", "Prompt Pattern Monitoring",
     "audit_monitoring",
     "Monitor Copilot prompts for high-risk keywords and data exfiltration patterns.",
     ["no_prompt_pattern_monitoring"],
     "MS Purview — Prompt Monitoring"),
    ("CTRL-OVR-011", "External Sharing Risk Scorecard",
     "oversharing_risk",
     "Composite risk score for external sharing exposure based on anonymous, external, and org-wide links.",
     ["external_sharing_risk_score"],
     "MS SharePoint — External Sharing Governance"),

    # ── Content Lifecycle Addition ──
    ("CTRL-CLM-004", "Legal Hold Compatibility",
     "content_lifecycle",
     "Ensure legal holds and eDiscovery holds preserve Copilot interaction data for litigation readiness.",
     ["no_legal_hold_configured"],
     "MS Purview — Legal Hold"),

    # ── Phase 5: App Protection, Label Encryption, RCD ──
    ("CTRL-GOV-021", "App Protection Policies (MAM)",
     "access_governance",
     "Intune App Protection Policies prevent Copilot-generated data from leaking to unmanaged apps on mobile devices.",
     ["no_app_protection_policies", "app_protection_platform_gaps"],
     "MS Intune — App Protection Policies"),
    ("CTRL-LBL-007", "Label Encryption & Site/Group Settings",
     "label_coverage",
     "Sensitivity labels with encryption enforce content-level access control; site/group settings protect containers.",
     ["labels_without_encryption", "labels_without_site_group_settings"],
     "MS Purview — Label Encryption"),
    ("CTRL-RSS-002", "Restricted Content Discoverability (RCD)",
     "restricted_search",
     "RCD limits which content Copilot can discover and surface, complementing RSS site-level restrictions.",
     ["rcd_not_configured"],
     "MS SharePoint — Restricted Content Discoverability"),

    # ── Phase 6: Checklist Gap Closure ──
    ("CTRL-CPS-014", "Cross-Tenant Access Policies",
     "copilot_security",
     "Cross-tenant access policies control B2B collaboration boundaries to prevent Copilot from surfacing external-tenant content without governance.",
     ["cross_tenant_access_not_assessed", "cross_tenant_access_permissive"],
     "MS Entra — Cross-Tenant Access"),
    ("CTRL-GOV-022", "Hybrid Identity Sync Health",
     "access_governance",
     "Ensure all hybrid-synced accounts have active Entra Connect sync so Copilot respects current on-premises permissions.",
     ["hybrid_accounts_stale_sync"],
     "MS Entra — Hybrid Identity"),
    ("CTRL-GOV-023", "Copilot License Segmentation",
     "access_governance",
     "Segment Copilot license assignment into pilot and production groups for phased, controlled rollout.",
     ["no_copilot_license_segmentation"],
     "MS Admin — Copilot License Segmentation"),
    ("CTRL-CPS-015", "Agent Approval Workflow",
     "copilot_security",
     "Require admin approval before users can publish Copilot agents to prevent ungoverned agent proliferation.",
     ["no_agent_approval_workflow"],
     "MS Copilot — Agent Approval"),
    ("CTRL-CPS-016", "External Connector Governance",
     "copilot_security",
     "Review and govern Graph connectors and external data connections that feed content into the Copilot search index.",
     ["ungoverned_external_connectors", "external_connector_review_needed"],
     "MS Graph — External Connectors"),
    ("CTRL-AUD-008", "Defender Copilot Incident Monitoring",
     "audit_monitoring",
     "Monitor Microsoft Defender for Copilot-related security incidents including data exfiltration and prompt injection.",
     ["copilot_security_incidents_detected"],
     "MS Defender — Copilot Incidents"),
    ("CTRL-CPS-017", "Prompt Guardrail Configuration",
     "copilot_security",
     "Configure prompt guardrails and content filters to prevent Copilot from generating sensitive or inappropriate content.",
     ["no_prompt_guardrails"],
     "MS Copilot — Prompt Guardrails"),
    # ── Zero Trust ──
    ("CTRL-ZT-001", "Continuous Access Evaluation (CAE)",
     "zero_trust",
     "Enable CAE to enforce near-real-time token revocation when user risk changes, preventing stale sessions from accessing Copilot data.",
     ["no_continuous_access_evaluation"],
     "MS Entra — Continuous Access Evaluation"),
    ("CTRL-ZT-002", "Token Protection (Token Binding)",
     "zero_trust",
     "Bind sign-in tokens to the device to prevent token theft and replay attacks that could grant unauthorized Copilot access.",
     ["no_token_protection"],
     "MS Entra — Token Protection"),
    ("CTRL-ZT-003", "Phishing-Resistant MFA",
     "zero_trust",
     "Require FIDO2, Windows Hello for Business, or certificate-based authentication instead of SMS/phone MFA to prevent credential theft.",
     ["no_phishing_resistant_mfa"],
     "MS Entra — Phishing-Resistant MFA"),
    ("CTRL-ZT-004", "Authentication Context for Sensitive Actions",
     "zero_trust",
     "Assign authentication contexts to sensitivity labels so accessing highly classified content via Copilot requires step-up authentication.",
     ["no_authentication_context"],
     "MS Entra — Authentication Context"),
    ("CTRL-ZT-005", "Workload Identity Protection",
     "zero_trust",
     "Apply risk policies to service principals and managed identities to detect anomalous workload identity behavior accessing Copilot data.",
     ["workload_identity_unprotected"],
     "MS Entra — Workload Identities"),
    ("CTRL-ZT-006", "Compliant Network Check",
     "zero_trust",
     "Require connections from compliant networks via Global Secure Access to access Copilot and M365 services.",
     ["no_compliant_network_check"],
     "MS Entra — Global Secure Access"),
    # ── Shadow AI ──
    ("CTRL-SAI-001", "Unauthorized AI App Detection",
     "shadow_ai",
     "Scan Entra app registrations for unauthorized third-party AI service integrations (OpenAI, Anthropic, Google AI, etc.).",
     ["unauthorized_ai_apps_detected"],
     "MS Entra — App Registrations"),
    ("CTRL-SAI-002", "AI OAuth Consent Grant Audit",
     "shadow_ai",
     "Review OAuth consent grants given to AI-related applications indicating user-initiated shadow AI adoption.",
     ["ai_consent_grants_detected"],
     "MS Entra — Consent Grants"),
    ("CTRL-SAI-003", "Shadow Copilot Agent Governance",
     "shadow_ai",
     "Detect user-created Copilot agents that bypass admin governance and may access sensitive organizational data.",
     ["shadow_copilot_agents_detected"],
     "MS Copilot — Agent Governance"),
    ("CTRL-SAI-004", "AI App Governance Policy",
     "shadow_ai",
     "Establish governance policies for AI application usage, including approval workflows and usage monitoring.",
     ["no_ai_app_governance"],
     "MS Defender — App Governance"),
    ("CTRL-SAI-005", "AI App Permission Boundary",
     "shadow_ai",
     "Ensure AI-related applications do not have excessive permissions that could lead to data exfiltration.",
     ["ai_apps_overpermissioned"],
     "MS Entra — App Permissions"),
    ("CTRL-SAI-006", "AI Data Exfiltration Prevention",
     "shadow_ai",
     "Configure Endpoint DLP or web content filtering to restrict data flow to unauthorized AI service domains.",
     ["no_ai_dlp_web_restrictions"],
     "MS Purview — Endpoint DLP"),
]


def build_security_controls_matrix(findings: list[dict]) -> list[dict]:
    """Build a complete M365 Copilot security controls status matrix.

    Maps each security control to its assessment status based on findings:
    - PASS: No gaps detected for this control
    - FAIL: One or more gaps exist
    - PARTIAL: Control is partially met
    - NOT_ASSESSED: Advisory control — requires manual verification
    """
    # Index findings by subcategory
    subcat_index: dict[str, dict] = {}
    for f in findings:
        sc = f.get("Subcategory", "")
        if sc:
            existing = subcat_index.get(sc)
            # Keep the highest-severity finding for each subcategory
            if existing is None or _SEVERITY_WEIGHTS.get(
                f.get("Severity", "").lower(), 0
            ) > _SEVERITY_WEIGHTS.get(
                existing.get("Severity", "").lower(), 0
            ):
                subcat_index[sc] = f

    controls: list[dict] = []
    for ctrl_id, name, category, description, mapped_subs, ms_ref in _COPILOT_SECURITY_CONTROLS:
        if not mapped_subs:
            # Advisory control — not directly assessed
            controls.append({
                "ControlId": ctrl_id,
                "ControlName": name,
                "Category": category,
                "Description": description,
                "Status": "NOT_ASSESSED",
                "Severity": "—",
                "Resource": "—",
                "Details": "Manual verification recommended",
                "MicrosoftReference": ms_ref,
                "MicrosoftReferenceUrl": _MS_REFERENCE_URLS.get(ms_ref, ""),
                "FindingRef": None,
            })
            continue

        # Check if any mapped subcategory has a finding
        matched_finding: dict | None = None
        for sc in mapped_subs:
            if sc in subcat_index:
                f = subcat_index[sc]
                if matched_finding is None or _SEVERITY_WEIGHTS.get(
                    f.get("Severity", "").lower(), 0
                ) > _SEVERITY_WEIGHTS.get(
                    matched_finding.get("Severity", "").lower(), 0
                ):
                    matched_finding = f

        if matched_finding:
            cs = matched_finding.get("ComplianceStatus", "gap").upper()
            status = "FAIL" if cs == "GAP" else "PARTIAL" if cs == "PARTIAL" else "PASS"
            resources = matched_finding.get("AffectedResources", [])
            res_name = resources[0].get("Name", "—") if resources else "—"
            controls.append({
                "ControlId": ctrl_id,
                "ControlName": name,
                "Category": category,
                "Description": description,
                "Status": status,
                "Severity": matched_finding.get("Severity", "—"),
                "Resource": res_name,
                "AffectedResources": resources,
                "Details": matched_finding.get("Title", ""),
                "MicrosoftReference": ms_ref,
                "MicrosoftReferenceUrl": _MS_REFERENCE_URLS.get(ms_ref, ""),
                "FindingRef": matched_finding.get("CopilotReadinessFindingId"),
            })
        else:
            # No finding means no issue detected — PASS
            controls.append({
                "ControlId": ctrl_id,
                "ControlName": name,
                "Category": category,
                "Description": description,
                "Status": "PASS",
                "Severity": "—",
                "Resource": "✓ No issues",
                "Details": "Control satisfied — no gaps detected",
                "MicrosoftReference": ms_ref,
                "MicrosoftReferenceUrl": _MS_REFERENCE_URLS.get(ms_ref, ""),
                "FindingRef": None,
            })

    return controls

